<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__minus</name>
   <tag></tag>
   <elementGuidId>9ec47c9e-c86d-48d1-9896-812eb6336012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-game.m-0.prev</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a2b5598-7415-4557-95b0-0e5db764db22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-game m-0 prev</value>
      <webElementGuid>0091b8e4-fae0-4b53-a659-df8ddffa504e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;hotline ng-tns-0-0&quot;]/app-root[1]/app-core[1]/div[@class=&quot;game-viewport&quot;]/div[@class=&quot;game-wrapper&quot;]/div[@class=&quot;game gui-bg-gradient&quot;]/div[@class=&quot;game-footer-wrapper&quot;]/div[@class=&quot;game-footer&quot;]/app-bet-controls[1]/div[@class=&quot;bet-controls&quot;]/div[@class=&quot;bet-input&quot;]/app-bet-input[1]/div[@class=&quot;bet-input ml-auto gui-bg&quot;]/div[@class=&quot;input-change d-flex justify-content-center align-items-center&quot;]/button[@class=&quot;btn btn-game m-0 prev&quot;]</value>
      <webElementGuid>ca533761-04d0-4e91-8d94-2311c1b82aa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>074665fd-1321-43e2-b5ab-f75c45aed5b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
