<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas</name>
   <tag></tag>
   <elementGuidId>c6a30733-8923-4e15-bdcf-4703f0d1dae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//canvas[@id = 'webgl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#webgl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='webgl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>016dc292-e243-46a8-86bb-ce255c365b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>webgl</value>
      <webElementGuid>c57ee6fa-bbe5-4c87-a33a-2643adfb12fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ee1258d6-4fec-4341-b5ec-ddd0b6722b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1920</value>
      <webElementGuid>38bdb11f-5cab-4297-96f1-803f3dd4a22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>827</value>
      <webElementGuid>2cd11f1d-0790-4fd5-9422-4927649f6d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webgl&quot;)</value>
      <webElementGuid>153c6b61-f3cf-4754-9c0a-6ea2239fcae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='webgl']</value>
      <webElementGuid>381bfa58-ff26-4008-aee7-c3545f6bac2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GameWrapper']/canvas</value>
      <webElementGuid>73debdb0-98b2-4eac-80ec-12773001ebd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>88e6f6b5-c947-4749-a793-ba4a4d5aa4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'webgl']</value>
      <webElementGuid>40a40366-46e2-4508-9cc3-63bdd0fc5db5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
