<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas</name>
   <tag></tag>
   <elementGuidId>404f3b31-9186-4e2a-9af4-efa246c42a4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#popup-container > div:nth-child(1) > button:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div/div[15]/section/div[1]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>5c0186e0-e978-4aa9-8749-736cbe851293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GameCanvas</value>
      <webElementGuid>1eec2a1b-9d4c-4c6c-8d98-5ac1768f2e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncontextmenu</name>
      <type>Main</type>
      <value>event.preventDefault()</value>
      <webElementGuid>8a7a7af8-9651-489a-abe4-97883c25326a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>99</value>
      <webElementGuid>73748d2d-8670-42da-a037-26ddff4b733e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gameCanvas</value>
      <webElementGuid>a90500f4-d91f-4b63-9f2c-be366240fe0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1920</value>
      <webElementGuid>30e63ead-1e21-419a-9249-5f3f5c265de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>911</value>
      <webElementGuid>c3872037-c706-4a1b-9024-916f92d7c88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GameCanvas&quot;)</value>
      <webElementGuid>cda8a870-cfdd-4f69-ad07-e6b6395ddee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='GameCanvas']</value>
      <webElementGuid>b68685ea-ab53-48fb-a034-5b03162655cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Cocos2dGameContainer']/canvas</value>
      <webElementGuid>1645fd9c-54fb-435c-b853-635d7d9b8774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>49bf83a5-7379-4e5f-9611-82aa40420601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'GameCanvas']</value>
      <webElementGuid>69fbe486-ba48-40ba-b6dc-4b2ba361efa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
