<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_All</name>
   <tag></tag>
   <elementGuidId>9d4f5d12-46d9-47f0-94db-339b8c2acf5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[normalize-space()='All']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;All&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4d9ecf9a-ae53-4a1b-a502-92285cfec4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>       
                All
                </value>
      <webElementGuid>31e0f803-a5af-4964-a069-6ecb5cbf47e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;desktop&quot;]/body[@class=&quot;bodyNoScroll&quot;]/div[@class=&quot;lang_us&quot;]/div[1]/div[1]/div[@class=&quot;gr_header__outer&quot;]/div[@class=&quot;gr_header  u_clearfix&quot;]/div[1]/div[@class=&quot;gr_header__game-menu gr_header__game-menu--black&quot;]/div[@class=&quot;gr_game-menu__content black&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;menu-container u_clearfix&quot;]/ul[1]/li[@class=&quot;gr_home__lottery__item&quot;]/div[1]</value>
      <webElementGuid>09b39869-5e60-4890-82e2-c8169173d698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VN 30s'])[1]/following::div[1]</value>
      <webElementGuid>3abceb33-906d-41c6-8931-73cdff51ba0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VN 5mins'])[1]/following::div[4]</value>
      <webElementGuid>a71fe912-2446-4bef-aaf1-0d8477e69a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='South'])[1]/preceding::div[3]</value>
      <webElementGuid>4707a0d1-50c7-4a85-8eca-8e03571b6457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Middle'])[1]/preceding::div[6]</value>
      <webElementGuid>46a84b7e-fef7-41de-b53a-ae26f69765be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All']/parent::*</value>
      <webElementGuid>c3537a71-c944-4f62-b75d-5cdc90470a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/div</value>
      <webElementGuid>b3791008-e1e0-45f0-9933-8c192b297769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '       
                All
                ' or . = '       
                All
                ')]</value>
      <webElementGuid>23b6e7f8-552e-4ae9-b7b8-2048a015022f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
