<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Pending  Cancelled</name>
   <tag></tag>
   <elementGuidId>875950ab-950e-4234-b839-2f4761f44701</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tab_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='open_bet_pending']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Pending / Cancelled&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8a1af927-e286-444a-8288-ac080bfd53e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab_label</value>
      <webElementGuid>ca4f664b-1844-438d-92b1-19c5e7e94a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pending / Cancelled </value>
      <webElementGuid>3907a181-55d6-4115-9984-0d10fca95f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;open_bet_pending&quot;)/div[@class=&quot;tab_label&quot;]</value>
      <webElementGuid>42edda8d-297e-443c-ade9-05f375c2a445</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='open_bet_pending']/div</value>
      <webElementGuid>b64e08c4-a328-4adc-9cf7-a56d57953f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Bets'])[1]/following::div[5]</value>
      <webElementGuid>3f9435bf-3536-4820-be8f-523f9b6ff3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Bets'])[1]/following::div[11]</value>
      <webElementGuid>e3631bd8-4db1-485c-87a1-efd857fc8d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmed'])[1]/preceding::div[1]</value>
      <webElementGuid>2d24af60-ad0c-47bd-8f66-8368e8e42cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Records'])[1]/preceding::div[3]</value>
      <webElementGuid>a686b392-b8fc-42ea-a6fd-ae60ebad96ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pending / Cancelled']/parent::*</value>
      <webElementGuid>1f3380e5-9e18-4df1-a3cd-cee448c607cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>0801989a-0fec-4d33-8ef0-11bb7b4e3e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pending / Cancelled ' or . = 'Pending / Cancelled ')]</value>
      <webElementGuid>981da33b-f030-4c31-838c-302ad733bb96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
