<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Today</name>
   <tag></tag>
   <elementGuidId>eaa9f820-cc6b-433b-b2a9-c4a53c8274ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.tab_label.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = '/' and (text() = ````'Today' or . = 'Today')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Today&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a7e8460-8de1-4f93-8640-84a2d6c8be63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>47549fcc-87b8-423e-8841-1d200bea78d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab_label  active</value>
      <webElementGuid>b9937cac-faa1-43aa-bdae-2876f9a71ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>6fafb5a6-55e2-4e4b-b19a-1403b62aad6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>c00008ab-2110-4f31-b7d9-5161f74c30fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left_panel&quot;)/div[@class=&quot;leftmenu_items sportsmenu&quot;]/div[@class=&quot;leftmenu_row_inner&quot;]/div[@class=&quot;sports_menu_contentwrap&quot;]/div[@class=&quot;leftmenu_tab_filter&quot;]/div[@class=&quot;leftmenu_tab_filter_inner active&quot;]/a[@class=&quot;tab_label  active&quot;]</value>
      <webElementGuid>4f0066af-770d-4b1b-97af-924d4465a9d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left_panel']/div[6]/div/div[2]/div[2]/div/a</value>
      <webElementGuid>07298eec-4c30-42d0-84e4-4980bf9510c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Today')]</value>
      <webElementGuid>917aea8c-b278-4417-b686-d7ed6e4be43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Sports'])[1]/following::a[1]</value>
      <webElementGuid>7f778336-7140-4a92-b365-58e430ebade9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBA - China Basketball Association'])[1]/following::a[2]</value>
      <webElementGuid>18cd3af5-131e-4036-80fe-2939e1fe891f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Early'])[1]/preceding::a[1]</value>
      <webElementGuid>91074310-98a3-4e4e-9a32-900978010281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soccer'])[1]/preceding::a[2]</value>
      <webElementGuid>2a16235c-f1ac-4b32-b789-09ed127d7471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Today']/parent::*</value>
      <webElementGuid>cf830fd3-8d4c-4603-b0a7-958dea70aa98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[12]</value>
      <webElementGuid>1b88575c-7192-4092-8981-89be42a3c22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a</value>
      <webElementGuid>38c655ef-58df-4099-b37c-9844da30a363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>4d41c060-7b01-4c84-b6f8-e5d774e43b6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
