<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Confirmed</name>
   <tag></tag>
   <elementGuidId>847d6efd-d581-4fbb-8848-2eee73f0c4e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#open_bet_confirm > div.tab_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='open_bet_confirm']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Confirmed&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c98873f3-40c2-4ed7-8077-8b8c07ea6411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab_label</value>
      <webElementGuid>8de32641-f9b3-4371-8c9f-07447449bf61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirmed</value>
      <webElementGuid>6560a97f-d2c0-4657-a39b-44deb861d777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;open_bet_confirm&quot;)/div[@class=&quot;tab_label&quot;]</value>
      <webElementGuid>a9216bf1-c38c-47a1-848f-ac09dd7d803d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='open_bet_confirm']/div</value>
      <webElementGuid>a3d1f8fd-cd92-4078-878d-8d004ca7e021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Bets'])[1]/following::div[7]</value>
      <webElementGuid>24223cf5-a7f9-4a6b-ad0d-cb8cd85c6d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Records'])[1]/preceding::div[1]</value>
      <webElementGuid>2a72aaf8-216b-4746-9ac4-7d5716bc8489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading'])[1]/preceding::div[6]</value>
      <webElementGuid>7999565b-6976-4b82-b002-0240be1d3b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirmed']/parent::*</value>
      <webElementGuid>814519fe-9d68-407d-a63a-56c5d94e6210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div</value>
      <webElementGuid>2fc297f4-7e9d-4450-b718-d0dea4b28c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Confirmed' or . = 'Confirmed')]</value>
      <webElementGuid>8357f63f-09f3-43d0-b30f-4a6069b73248</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
