<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Live</name>
   <tag></tag>
   <elementGuidId>0f6ad42e-2e39-490e-bd7a-399682da9ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leftpanel_live > div.leftmenu_row_inner > div.sports_menu_header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftpanel_live']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Live$/ >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>54bc6228-0c4b-49e8-82ec-906ca1631fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sports_menu_header</value>
      <webElementGuid>0cb5d894-c1ba-42a7-a072-d7278a70a79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Live</value>
      <webElementGuid>89e298c1-d8fe-4847-9cf1-badaf4c43d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftpanel_live&quot;)/div[@class=&quot;leftmenu_row_inner&quot;]/div[@class=&quot;sports_menu_header&quot;]</value>
      <webElementGuid>609ab1b9-9816-4a93-a380-52d79bc05247</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftpanel_live']/div/div</value>
      <webElementGuid>e2452b92-183c-4036-aa61-bccc6665b05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Bets'])[1]/following::div[6]</value>
      <webElementGuid>2e07bd9c-5916-43f7-b28a-d536b3134005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Bets'])[1]/following::div[12]</value>
      <webElementGuid>36266c89-38f7-4651-8732-65afb8dcaecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div</value>
      <webElementGuid>13227f71-55a5-49ae-a3ee-1966acd26ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Live' or . = 'Live')]</value>
      <webElementGuid>ef11dad7-e8e7-4234-813d-76b5bf56637d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
