<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_MyBets</name>
   <tag></tag>
   <elementGuidId>ad3be07c-ce86-49a8-942e-f2e00abc5d52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sports_menu_header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftpanel_mybet']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^My Bets$/ >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e85434ca-3d6a-4b7b-b20b-4afaaa198d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sports_menu_header</value>
      <webElementGuid>359ec63c-42d2-4a3b-8e1f-e68fb0291a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Bets</value>
      <webElementGuid>70e12745-b953-4449-89b0-f8b42510bfb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftpanel_mybet&quot;)/div[@class=&quot;leftmenu_row_inner&quot;]/div[@class=&quot;sports_menu_header&quot;]</value>
      <webElementGuid>ee3ade58-4d80-4bd8-9d2a-db2d2e5858c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftpanel_mybet']/div/div</value>
      <webElementGuid>f72d08ba-c9de-4f07-8a37-052ff878e2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Bets'])[1]/following::div[4]</value>
      <webElementGuid>cbc9b262-2d56-4392-8f6e-43463f40d95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance'])[1]/following::div[7]</value>
      <webElementGuid>3c5d7bdc-1572-4bf2-95d8-dbe4e6f0ee41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live'])[1]/preceding::div[6]</value>
      <webElementGuid>87b946c8-4adb-4e58-834d-4d91bfebd682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>a8944dfd-8c81-4816-ae00-7ffbdff3f6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'My Bets' or . = 'My Bets')]</value>
      <webElementGuid>067608ff-c277-4c32-815e-f0886261f6f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
