<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_07</name>
   <tag></tag>
   <elementGuidId>2987d9e7-7c11-4b52-b1da-61452fb01b0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='betPage1_0']/ul/li[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;07&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b2cd66b9-14a6-4550-a7c7-018752d3d658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>fb8bbff6-994a-4b1e-aebc-c7f14eefe6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xz_list1_right_num</value>
      <webElementGuid>ece9a444-b686-48e9-8ceb-5e04ab799a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>07</value>
      <webElementGuid>b1d0c879-0a46-48ea-a1de-a550d52a139c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;betPage1_0&quot;)/ul[@class=&quot;xz_list1_right&quot;]/li[@class=&quot;betPage1_betField_0&quot;]/a[@class=&quot;xz_list1_right_num&quot;]</value>
      <webElementGuid>3e2dee73-e535-474c-893b-c692443a2e6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='betPage1_0']/ul/li[8]/a</value>
      <webElementGuid>3f39e444-11b6-4c75-a389-ae61feef971b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'07')]</value>
      <webElementGuid>c97e343c-309c-45ca-965d-789d0feab54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示遗漏'])[1]/following::a[8]</value>
      <webElementGuid>fbea6188-b8fd-44ef-9424-2aa218b24f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示冷热'])[1]/following::a[8]</value>
      <webElementGuid>dda5eced-2d7a-43b3-a2af-0cea3d8caed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全'])[1]/preceding::a[5]</value>
      <webElementGuid>aa9a5c01-298d-4d0f-8f82-3ae037802610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='大'])[1]/preceding::a[6]</value>
      <webElementGuid>95aeef75-8781-4a9a-b2d3-23630bc9bcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='07']/parent::*</value>
      <webElementGuid>fbc62774-0ce3-4243-8fa8-839ad68c799c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[8]</value>
      <webElementGuid>f77294ba-3728-4c88-88cd-1ef284c49639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[8]/a</value>
      <webElementGuid>f11f083e-c59c-4bda-a7b2-67b3f584182e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = '07' or . = '07')]</value>
      <webElementGuid>4ed30e72-09c3-4634-adc3-c6db9a67a311</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
