<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_EVEN</name>
   <tag></tag>
   <elementGuidId>6b8e465e-c612-4c70-9705-d23b08a854ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.bigSmall_btn.betPage1_quickChoose_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@class='bigSmall_btn betPage1_quickChoose_4'][contains(text(),'双')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;全&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e19c607b-3e0f-4fd4-8e3d-07379d6d6572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>08b313b2-6736-4663-8c2b-94f71078bedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bigSmall_btn betPage1_quickChoose_0</value>
      <webElementGuid>cd03c114-6594-4058-9d9a-5e7e368b180f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>choosetype</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>624e4d04-596a-434d-817c-a009f0c1f2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row_num</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c66f2135-a54e-4bdd-946a-cbf0828416d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>全</value>
      <webElementGuid>885c16e3-050c-4e89-a339-d725174baef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;betPage1_0&quot;)/div[@class=&quot;bigSmall&quot;]/a[@class=&quot;bigSmall_btn betPage1_quickChoose_0&quot;]</value>
      <webElementGuid>3670d6a4-59bb-470e-a278-75c64669a044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='betPage1_0']/div[2]/a</value>
      <webElementGuid>c6919e9c-f585-4fed-917b-08ce86c757fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'全')])[2]</value>
      <webElementGuid>6d19c7e1-a31c-4225-a652-c42479065319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示遗漏'])[1]/following::a[13]</value>
      <webElementGuid>126af571-32ad-4935-ad22-6cfafefb2365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示冷热'])[1]/following::a[13]</value>
      <webElementGuid>6968a0f8-bf93-43c7-b344-c684cacb4ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='大'])[1]/preceding::a[1]</value>
      <webElementGuid>2d7197f8-cee6-4726-8b7d-a77ec19580a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='小'])[1]/preceding::a[2]</value>
      <webElementGuid>2377b355-7cfb-491b-9bd4-4fa6b83b4c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='全']/parent::*</value>
      <webElementGuid>2b8d87a7-a08d-4530-aea5-0a19d3eb8be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[13]</value>
      <webElementGuid>a39933f6-2c09-4524-ba6b-a5eddea8c146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>2829fcf7-6aed-42d4-996c-63cefb643c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = '全' or . = '全')]</value>
      <webElementGuid>e0f6db04-fdb1-4ace-8122-51c26c77f6a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
