<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ALL</name>
   <tag></tag>
   <elementGuidId>2681f069-7ad7-4c78-81aa-b2218878fcc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.bigSmall_btn.betPage1_quickChoose_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@class='bigSmall_btn betPage1_quickChoose_0'][contains(text(),'全')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;全&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>46b433a4-2923-4334-8367-a28c57a3b30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>e07929bb-3a3c-4ad9-b2e7-e486a172e41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bigSmall_btn betPage1_quickChoose_0</value>
      <webElementGuid>c28b1e1e-189b-474d-a985-9f3c6bc1b8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>choosetype</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0654af6f-a359-4ebf-84cc-30a6fe9ceb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row_num</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e819dbb6-e9f7-47f1-9030-8c4420dd11c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>全</value>
      <webElementGuid>b8306cd3-8230-4b90-9550-01bf729dd11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;betPage1_0&quot;)/div[@class=&quot;bigSmall&quot;]/a[@class=&quot;bigSmall_btn betPage1_quickChoose_0&quot;]</value>
      <webElementGuid>bffecb3a-b266-4b1d-a33a-4e4b07cbbee6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='betPage1_0']/div[2]/a</value>
      <webElementGuid>0a79310b-d447-4b54-9dc6-822c149b3208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'全')])[2]</value>
      <webElementGuid>cf6b6351-3970-429b-89dc-71dc2f3b02b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示遗漏'])[1]/following::a[13]</value>
      <webElementGuid>ae2558f9-66e6-4145-bf43-9f3207de20cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示冷热'])[1]/following::a[13]</value>
      <webElementGuid>b83fb173-02f8-465b-ac88-10ee0396d01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='大'])[1]/preceding::a[1]</value>
      <webElementGuid>b138e70f-a83f-4645-aa80-8608287d4b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='小'])[1]/preceding::a[2]</value>
      <webElementGuid>69ea8216-53c7-4ff5-a359-f21c6dc4c88a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='全']/parent::*</value>
      <webElementGuid>1cccf981-267e-4b26-858f-6afccfb91240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[13]</value>
      <webElementGuid>f6cc9e45-8ed5-457e-ba0d-a6cf345ce592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>c1a079ce-3319-4370-8866-448cee9116cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = '全' or . = '全')]</value>
      <webElementGuid>2dd37abc-bb9d-45c9-a936-8b237e8e10fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
