<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SMALL</name>
   <tag></tag>
   <elementGuidId>f1e8c5d9-649e-4654-8989-9de786a99fc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.bigSmall_btn.betPage1_quickChoose_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@class='bigSmall_btn betPage1_quickChoose_2'][contains(text(),'小')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;全&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1920f9c9-f6d8-4f63-ad3f-7b0ed39d87d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>b0a071fd-4291-4e3d-911c-2397d31b2a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bigSmall_btn betPage1_quickChoose_0</value>
      <webElementGuid>7e0cdef3-17bc-43bb-8aa2-d4fa572ef707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>choosetype</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>091b6344-12cd-421d-a9d1-d941594604c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row_num</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>82ac602f-9aed-4cbe-8c7d-c777330d4b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>全</value>
      <webElementGuid>3c473c1b-9607-45b7-9643-0308dec45c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;betPage1_0&quot;)/div[@class=&quot;bigSmall&quot;]/a[@class=&quot;bigSmall_btn betPage1_quickChoose_0&quot;]</value>
      <webElementGuid>efa4496d-dcdf-45be-81b5-763d48b59f66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='betPage1_0']/div[2]/a</value>
      <webElementGuid>6156251b-dbde-4ac3-8580-e52066335968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'全')])[2]</value>
      <webElementGuid>11a0a9a7-e9ed-4fc3-b5fa-e3c0061a9d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示遗漏'])[1]/following::a[13]</value>
      <webElementGuid>837e1e27-9760-4a2e-955e-197b0a8a3507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示冷热'])[1]/following::a[13]</value>
      <webElementGuid>499ef62e-4942-401c-ae5d-cf4cc20dddc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='大'])[1]/preceding::a[1]</value>
      <webElementGuid>597f4842-30a0-4769-91ff-62c5203104b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='小'])[1]/preceding::a[2]</value>
      <webElementGuid>45b3c087-3459-498e-a308-72c1c8a8e806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='全']/parent::*</value>
      <webElementGuid>4010f76f-79e4-43f8-a4c9-27008101563a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[13]</value>
      <webElementGuid>8d9ae91b-4c24-4f32-92a6-6bab3995a20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>94d9f2ec-14ec-4b1d-8047-878d045f06e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = '全' or . = '全')]</value>
      <webElementGuid>6773ef33-abfe-4adb-91e0-957a5babb799</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
