<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_BIG</name>
   <tag></tag>
   <elementGuidId>71bea654-1683-4704-b6c5-20eed475fa5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.bigSmall_btn.betPage1_quickChoose_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@class='bigSmall_btn betPage1_quickChoose_1'][contains(text(),'大')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;全&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d0143d89-ee64-407b-b7c6-42b0159cafd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>4ff2c606-2ac5-4a05-9092-c116a1576330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bigSmall_btn betPage1_quickChoose_0</value>
      <webElementGuid>58a54074-e032-4137-8eba-dd2b4cb0411d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>choosetype</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a6141f22-70e8-4b6d-9c57-8212619993fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row_num</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>256642ae-c622-4022-bbbf-5ac22be31d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>全</value>
      <webElementGuid>431863b7-a65b-46eb-b48d-def86bed2543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;betPage1_0&quot;)/div[@class=&quot;bigSmall&quot;]/a[@class=&quot;bigSmall_btn betPage1_quickChoose_0&quot;]</value>
      <webElementGuid>d03750e0-06f3-45dc-afda-df77bb8d11f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='betPage1_0']/div[2]/a</value>
      <webElementGuid>96cd2598-4e3b-4aa7-90f1-330622a68c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'全')])[2]</value>
      <webElementGuid>47655782-264e-4584-8915-09453df76f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示遗漏'])[1]/following::a[13]</value>
      <webElementGuid>1283875d-9897-43e8-9068-d890cbc132a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示冷热'])[1]/following::a[13]</value>
      <webElementGuid>b1daae49-5faf-4380-9322-2ff221726f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='大'])[1]/preceding::a[1]</value>
      <webElementGuid>2f381b1c-a59a-447f-ac60-5af4668a985d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='小'])[1]/preceding::a[2]</value>
      <webElementGuid>145bfba8-589f-49f2-b41f-5758d4855a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='全']/parent::*</value>
      <webElementGuid>0e383975-1c19-44ee-b230-ed337e374a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[13]</value>
      <webElementGuid>d8c74eab-2f5e-49ac-a157-001eda335b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>6dc9cd00-cc48-4adf-84ca-229f1c83d609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = '全' or . = '全')]</value>
      <webElementGuid>55abeca1-ccf4-4cbe-8503-641cabc6ae04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
