<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ODD</name>
   <tag></tag>
   <elementGuidId>aa2aafc7-55e7-4b07-9faf-dd1299da0b70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.bigSmall_btn.betPage1_quickChoose_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@class='bigSmall_btn betPage1_quickChoose_3'][contains(text(),'单')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;全&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a6a9839-8e7b-4175-b66a-87877fc363ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>48bab8f6-2632-409c-89ca-2fff1f60f3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bigSmall_btn betPage1_quickChoose_0</value>
      <webElementGuid>c30052cc-1393-4fff-afc8-dde449ecd7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>choosetype</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c6d5f6a0-fd97-40b6-9539-a78cf1a57ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row_num</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dd6618db-f7d0-4753-8277-89bfe378dbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>全</value>
      <webElementGuid>ce8dda6c-5d73-443d-b28a-8857e2001a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;betPage1_0&quot;)/div[@class=&quot;bigSmall&quot;]/a[@class=&quot;bigSmall_btn betPage1_quickChoose_0&quot;]</value>
      <webElementGuid>1e05fa78-d061-43c6-aa1e-ead483b5b707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='betPage1_0']/div[2]/a</value>
      <webElementGuid>6a26ae5e-7c4d-448c-81fd-5b85b0164bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'全')])[2]</value>
      <webElementGuid>f83ec343-1f66-4984-a92f-305fc1dd0a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示遗漏'])[1]/following::a[13]</value>
      <webElementGuid>270b9c74-4ed2-4a54-88ee-b75b6365ddfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示冷热'])[1]/following::a[13]</value>
      <webElementGuid>7984949f-f31a-49f5-b11b-8724d47d27b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='大'])[1]/preceding::a[1]</value>
      <webElementGuid>1274c3b2-2baa-4f00-a12e-9eee47850b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='小'])[1]/preceding::a[2]</value>
      <webElementGuid>054a9a8f-b2fa-4f09-94e9-e64ab6e8d8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='全']/parent::*</value>
      <webElementGuid>fa844d2a-a079-4e46-bb2d-919d8d39c2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[13]</value>
      <webElementGuid>90727bb3-0c55-436d-889f-293c011419aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>0c4521a8-5caf-47f8-a1fd-34823fbbd23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = '全' or . = '全')]</value>
      <webElementGuid>3009802b-a2c1-4565-80a9-6220fca5222c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
