<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>balance</name>
   <tag></tag>
   <elementGuidId>5918b519-62b3-4372-a00d-67d10595cf24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '                                                            Bet                1.00                Free                                                                                                        0.501.001.502.002.505.0010.0015.0020.0025.0050.00100.00150.00200.00250.00400.00600.00800.001,000.00                                                                        Credits                        1.00                        Free                                                                                                                                        Credits                        50                        Free                                                                                                                                        Value                        0.01                        Free                                                                                                                                        Level                        2                        Free                                                                                                                                                                                 Total Bet                1.00                                         10702822                                        Good Day                                                            Balance                19,698.63                                                                                                                    ' or . = '                                                            Bet                1.00                Free                                                                                                        0.501.001.502.002.505.0010.0015.0020.0025.0050.00100.00150.00200.00250.00400.00600.00800.001,000.00                                                                        Credits                        1.00                        Free                                                                                                                                        Credits                        50                        Free                                                                                                                                        Value                        0.01                        Free                                                                                                                                        Level                        2                        Free                                                                                                                                                                                 Total Bet                1.00                                         10702822                                        Good Day                                                            Balance                19,698.63                                                                                                                    ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.controlbar_top_main</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;controlbarH5&quot;]/div[1]/div[4]/div/div[1]/div/div[3]/div[4]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b05c9ca-34a7-4c32-9e73-a02253b60715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>controlbar_top_main</value>
      <webElementGuid>866236d2-95ed-4a80-b142-f9d847e1f7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                                                            Bet                1.00                Free                                                                                                        0.501.001.502.002.505.0010.0015.0020.0025.0050.00100.00150.00200.00250.00400.00600.00800.001,000.00                                                                        Credits                        1.00                        Free                                                                                                                                        Credits                        50                        Free                                                                                                                                        Value                        0.01                        Free                                                                                                                                        Level                        2                        Free                                                                                                                                                                                 Total Bet                1.00                                         10702822                                        Good Day                                                            Balance                19,698.63                                                                                                                    </value>
      <webElementGuid>88eed0b5-a4fc-410e-a3b8-a33df6a51df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;controlbarH5&quot;)/div[@class=&quot;controlbarChild&quot;]/div[@class=&quot;controlbar_new_web&quot;]/div[@class=&quot;controlbarMain&quot;]/div[@class=&quot;controlbar_top clearfix&quot;]/div[@class=&quot;controlbar_top_main&quot;]</value>
      <webElementGuid>1a9cfa45-c301-48f0-b5c2-6ad0a9a6b3a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='controlbarH5']/div/div[4]/div/div/div</value>
      <webElementGuid>24f2f4a2-68e0-4e46-b933-396b1da11227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance'])[1]/following::div[4]</value>
      <webElementGuid>7b7d995d-3e56-44ae-ad25-b29492c7f77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good Day'])[1]/following::div[5]</value>
      <webElementGuid>75d9f4b6-9ef9-40ae-98aa-8fe714bffb38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div</value>
      <webElementGuid>94e6dd77-db33-4907-a91a-03288365c800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '                                                            Bet                1.00                Free                                                                                                        0.501.001.502.002.505.0010.0015.0020.0025.0050.00100.00150.00200.00250.00400.00600.00800.001,000.00                                                                        Credits                        1.00                        Free                                                                                                                                        Credits                        50                        Free                                                                                                                                        Value                        0.01                        Free                                                                                                                                        Level                        2                        Free                                                                                                                                                                                 Total Bet                1.00                                         10702822                                        Good Day                                                            Balance                19,698.63                                                                                                                    ' or . = '                                                            Bet                1.00                Free                                                                                                        0.501.001.502.002.505.0010.0015.0020.0025.0050.00100.00150.00200.00250.00400.00600.00800.001,000.00                                                                        Credits                        1.00                        Free                                                                                                                                        Credits                        50                        Free                                                                                                                                        Value                        0.01                        Free                                                                                                                                        Level                        2                        Free                                                                                                                                                                                 Total Bet                1.00                                         10702822                                        Good Day                                                            Balance                19,698.63                                                                                                                    ')]</value>
      <webElementGuid>dea4b8bf-1da3-407b-816a-dfb46caf4e07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
