<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_icon-spin</name>
   <tag></tag>
   <elementGuidId>a2f37d9c-b8bf-4dd0-bd18-9a763f9b5ad9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='PlaceBetBtn']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PlaceBetBtn > span.icon-spin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b5888804-abf7-4976-ad02-6c6692ae1fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-spin</value>
      <webElementGuid>84cfe349-f480-4546-a79a-ab8d363f874b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PlaceBetBtn&quot;)/span[@class=&quot;icon-spin&quot;]</value>
      <webElementGuid>3477cb1f-5259-4069-a83c-f66a5899c6e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='PlaceBetBtn']/span</value>
      <webElementGuid>aaa46066-6c8c-4605-9303-ff45c45acbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div[2]/button[2]/span</value>
      <webElementGuid>36a9a26e-9ed2-4782-811c-23da76d03aa3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
