<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_icon-arrow-up</name>
   <tag></tag>
   <elementGuidId>e360f4f2-b453-4894-a0e4-bf23e14c4688</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BetAmountIncrease']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BetAmountIncrease > span.icon-arrow-up</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0df9662e-29db-45f4-b408-d97574d892b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-arrow-up</value>
      <webElementGuid>f6512505-6f3b-4e00-a1fe-31cfdb1e6c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BetAmountIncrease&quot;)/span[@class=&quot;icon-arrow-up&quot;]</value>
      <webElementGuid>f375ef37-3dc9-4ee4-a2b7-a9d52c40f272</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='BetAmountIncrease']/span</value>
      <webElementGuid>0d86d6fd-ebeb-49a0-a31c-6b3aa0c6faef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>3a6d9854-6157-47cc-9bce-f8f4fc2d3c72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
