<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Close</name>
   <tag></tag>
   <elementGuidId>4cc22f22-3f89-41e6-ad84-ba20c72e7f9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'FeatureBuyClose' and (text() = 'Close' or . = 'Close')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FeatureBuyClose</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#FeatureBuyClose</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c8772e67-d10c-42b4-ae13-dc05f4950ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FeatureBuyClose</value>
      <webElementGuid>3459ad0c-8b1b-43db-907c-c3d7e81e802f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FeatureBuy__close</value>
      <webElementGuid>732db752-1931-46e3-8a09-aa771388a432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-translation</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>b418c3d7-9626-46ee-a3ab-83ea5577306d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-charcount</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>22ac1e73-7df3-498c-97b0-f3d0b35f7d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>e60a58e0-ad4c-48a1-8e52-1ada71bf2b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FeatureBuyClose&quot;)</value>
      <webElementGuid>18be542f-7a15-4169-8d83-b3fcad705cfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='FeatureBuyClose']</value>
      <webElementGuid>0f6b0a91-d441-4270-a4a3-6352015681d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FeatureBuyWindow']/div[2]/div</value>
      <webElementGuid>423c663a-7ec6-4e8c-8588-66288e079909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/following::div[4]</value>
      <webElementGuid>82d18a30-135c-447a-9789-1fb74ebdc6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WIN'])[1]/following::div[4]</value>
      <webElementGuid>53626d0d-b014-4a3a-b8ea-0b6dbacdebc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BONUS BUY'])[1]/preceding::div[1]</value>
      <webElementGuid>e64a91df-2e58-46ad-81f0-dccff7dffcaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BET'])[2]/preceding::div[2]</value>
      <webElementGuid>3f185957-062b-476a-8417-8907e36a59b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div</value>
      <webElementGuid>b809b01e-8363-49db-9a38-f010013042bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'FeatureBuyClose' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>ffa06a0d-518d-4942-8e7e-12a4da8fe76a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
