<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_icon-menu</name>
   <tag></tag>
   <elementGuidId>818bb3f1-22f1-4818-8c44-c8ea4aaf9ea9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MainMenuToggle']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon-menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MainMenuToggle span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dfad9550-1748-47e8-8f47-39ab0b2d7378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-menu</value>
      <webElementGuid>13bf3f64-8505-441f-957e-7e11beb978a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainMenuToggle&quot;)/span[@class=&quot;icon-menu&quot;]</value>
      <webElementGuid>0d5fa8b3-d83b-4ae5-ab55-2073526bdae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainMenuToggle']/span</value>
      <webElementGuid>69465a6b-a792-481e-942d-ab13c3500b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/span</value>
      <webElementGuid>61e7bc7c-d366-4236-886d-3e3d43035b80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
