<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_icon-arrow-down</name>
   <tag></tag>
   <elementGuidId>23482ae3-ae73-4068-9877-81b018c17f3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BetAmountDecrease']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BetAmountDecrease > span.icon-arrow-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06294653-f174-4754-97cf-4f376f7e993c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-arrow-down</value>
      <webElementGuid>5a330092-ba0b-47ce-843a-13f79d6c197f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BetAmountDecrease&quot;)/span[@class=&quot;icon-arrow-down&quot;]</value>
      <webElementGuid>53f272e3-975c-4af0-8c59-68764e710c98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='BetAmountDecrease']/span</value>
      <webElementGuid>4582d099-677c-4b2b-97b3-8728d82237dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]/span</value>
      <webElementGuid>2c041453-e858-43d0-bc5b-5560d041c003</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
