<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AutoplayBtn</name>
   <tag></tag>
   <elementGuidId>c9fe0214-2e11-4c6d-ae3e-924543cef48a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='AutoplayBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AutoplayBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75cd041a-4b04-4829-8314-026f8d68da76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AutoplayBtn</value>
      <webElementGuid>98e23af3-c2a3-494d-919e-d1cf7e215eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Menu-trigger Button</value>
      <webElementGuid>2ee1dcb7-5ce1-467d-8469-8b3b8bf066dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AutoplayBtn&quot;)</value>
      <webElementGuid>30c9b2cb-d4e2-4a24-8162-7ac8098b9adb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='AutoplayBtn']</value>
      <webElementGuid>820c19c0-727d-4f56-a627-77c37d81a1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ActionPanel']/button</value>
      <webElementGuid>05bab4b5-2af7-45c5-a88b-57a25ce954df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥10.00'])[3]/following::button[1]</value>
      <webElementGuid>7011457b-9c1a-4ecd-a92a-0a2cc4e06c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BET'])[4]/following::button[1]</value>
      <webElementGuid>c2b6f0a6-8074-4c49-afd5-72e967716779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BASIC'])[1]/preceding::button[4]</value>
      <webElementGuid>604f2640-bc2a-415f-9965-97b17ed3ee7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUTOPLAY'])[1]/preceding::button[4]</value>
      <webElementGuid>02fb61dc-872f-4154-a4b8-b867c10312f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div[2]/button</value>
      <webElementGuid>2108eaf5-c3b2-49f3-b47a-62a489fdc8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'AutoplayBtn']</value>
      <webElementGuid>72986fa5-920d-4fc9-ade7-d746c6212e3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
