<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All</name>
   <tag></tag>
   <elementGuidId>b64b8593-6b28-4e1f-a56f-04426f56e827</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.gr_controller__group > li.gr_group__item.is_active > span.gr_item__text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[3]/div[2]/div[1]/div[3]/ul[1]/li[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;All&quot;s >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3fd8084f-c32f-40e0-b384-56c8b7327b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gr_item__text</value>
      <webElementGuid>d40d445d-b8cf-462c-9d7f-03cd9097a515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>7168197f-5995-44ca-b933-342409d807bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;desktop&quot;]/body[1]/div[@class=&quot;lang_us&quot;]/div[1]/div[1]/div[2]/div[3]/div[@class=&quot;gr_container  bg_primary&quot;]/div[@class=&quot;gr_official&quot;]/div[@class=&quot;gr_official__section  u_clearfix&quot;]/div[@class=&quot;gr_section__controller&quot;]/ul[@class=&quot;gr_controller__group&quot;]/li[@class=&quot;gr_group__item is_active&quot;]/span[@class=&quot;gr_item__text&quot;]</value>
      <webElementGuid>567fff13-146a-46ac-9128-18f768c590ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Pair'])[1]/following::span[11]</value>
      <webElementGuid>42824637-f355-4732-8c32-ebc17f5351f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Example：'])[1]/following::span[14]</value>
      <webElementGuid>6de3d97a-c945-4b26-8b6b-a8dfe506dd6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Big'])[1]/preceding::span[1]</value>
      <webElementGuid>57e5e7d6-64cc-453e-aa60-dbbdafa9540e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Small'])[1]/preceding::span[2]</value>
      <webElementGuid>5022a1c2-3363-4f4a-95a9-b559d4019243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All']/parent::*</value>
      <webElementGuid>56c3478f-f005-4b38-8455-532ca4721571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[3]/ul/li/span</value>
      <webElementGuid>9ee2fbb0-c869-424f-a64c-a4d7cb471479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'All' or . = 'All')]</value>
      <webElementGuid>3eff6543-cbb9-46e3-bbe5-c59df80af502</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
