<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_5</name>
   <tag></tag>
   <elementGuidId>ad9ec19a-c6c7-4bb0-b117-5f4b5f9fd68f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li[name=&quot;TC3D&quot;] > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'排列5')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;排列5&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d415132-1c38-45fe-823d-97f7525f0d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>00d0d312-356d-4546-9db2-3e42daab8aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>排列5</value>
      <webElementGuid>cc460ec9-13ef-482d-8d8e-c2844f4c4d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBody&quot;)/div[@class=&quot;gfcMainPage&quot;]/div[@class=&quot;top_content&quot;]/ul[@class=&quot;title-menu&quot;]/li[@class=&quot;biankuang bg_color1&quot;]/a[1]</value>
      <webElementGuid>bf1dd1ca-68e9-462d-a908-6ff176de7ade</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='mainBody']/div/div/ul/li[6]/a</value>
      <webElementGuid>3192d454-b3f9-4472-873a-86165cf1d3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'排列5')]</value>
      <webElementGuid>abe02a6c-9d5d-44ed-bc35-af3b69700d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='时时彩'])[1]/following::a[3]</value>
      <webElementGuid>21074a78-4c6a-4285-816f-930395fe1514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PK10'])[1]/following::a[4]</value>
      <webElementGuid>ec53659a-d407-40ff-bd28-6f87546d6d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='快3'])[1]/preceding::a[1]</value>
      <webElementGuid>7ac57696-5d92-4077-95ed-93a03cd6cc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全部彩种列表'])[1]/preceding::a[2]</value>
      <webElementGuid>58b6e73d-efa9-4c0f-a2f1-64fd6eebab17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='排列5']/parent::*</value>
      <webElementGuid>159de927-84c3-4174-8737-d21d58e964a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[6]</value>
      <webElementGuid>17d6982c-bff4-4d5b-8509-e8b6a7717e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>3f19a098-571a-4aca-a9b8-b5cb07e7830d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '排列5' or . = '排列5')]</value>
      <webElementGuid>550c1929-4733-42e8-b566-555ca4e000cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
