<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_3</name>
   <tag></tag>
   <elementGuidId>85a2ac21-2073-4bb5-8343-af469d93d8db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.end_semicircle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'快3')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;快3&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>006f3300-5342-4d02-a9a6-e38dfb9c80ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>6dd38ac3-ff98-4ea4-9ee4-fd4c278a9647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>end_semicircle</value>
      <webElementGuid>f695ddf4-7d1d-4515-9a9a-e4151fa126e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>快3</value>
      <webElementGuid>825f9b57-f65c-4dfa-92f1-48111fdaa448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBody&quot;)/div[@class=&quot;gfcMainPage&quot;]/div[@class=&quot;top_content&quot;]/ul[@class=&quot;title-menu&quot;]/li[@class=&quot;bg_color1&quot;]/a[@class=&quot;end_semicircle&quot;]</value>
      <webElementGuid>4f00308d-50aa-4d79-ab93-f6a03fc877d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='mainBody']/div/div/ul/li[7]/a</value>
      <webElementGuid>b686f62a-9ec9-4a55-85ec-c58a2d82481b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'快3')]</value>
      <webElementGuid>07c98e69-f51f-42c4-8022-3d79b0f0e46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='排列5'])[1]/following::a[1]</value>
      <webElementGuid>ce97dc36-06e4-4b22-8b01-36f2a86a11b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='时时彩'])[1]/following::a[4]</value>
      <webElementGuid>1de7be8c-c0c5-4e88-8fa0-950b98f2b437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全部彩种列表'])[1]/preceding::a[1]</value>
      <webElementGuid>02df656f-730d-49c4-9331-1799d0bb9a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='极速赛车'])[1]/preceding::a[2]</value>
      <webElementGuid>000e2666-0f66-410e-bca5-c80ea849a0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='快3']/parent::*</value>
      <webElementGuid>2a678108-d644-4f2f-9609-e67bf90dc322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[7]</value>
      <webElementGuid>af17efd8-5bf7-4615-81fc-65ed38128cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>aa1b478e-a98c-4c61-abc6-5d3df9d03bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '快3' or . = '快3')]</value>
      <webElementGuid>552983c5-a472-4f2b-a3b8-6165a4b216a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
