<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_PK10</name>
   <tag></tag>
   <elementGuidId>b5ee2bfe-4580-4b6a-998f-4f9e142a3971</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ig_inlet_pk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ig_inlet_pk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;PK10&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb64e338-04dc-408d-9a9a-dcfcfc917a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ig_inlet_pk</value>
      <webElementGuid>83ae8166-c922-4c78-b74d-cc3249bb9dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>cc84e640-dc87-4641-88e3-e3df1d47e75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PK10</value>
      <webElementGuid>848c41e7-f686-469b-a464-22d83f0f250e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ig_inlet_pk&quot;)</value>
      <webElementGuid>7cfaaee8-806e-4b1c-8431-92547a57e46c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ig_inlet_pk']</value>
      <webElementGuid>1954264a-7d66-466e-8d99-af4cc45a89aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='mainBody']/div/div/ul/li[2]/a</value>
      <webElementGuid>dae55275-eb89-4f2f-bfc9-8daad3589abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PK10')]</value>
      <webElementGuid>04a2374f-04f6-47d2-949c-281543384789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我的收藏'])[1]/following::a[1]</value>
      <webElementGuid>ffd93b1b-e58c-44f6-98cb-1cb2dd149901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='时时彩'])[1]/preceding::a[1]</value>
      <webElementGuid>379dca01-02fe-41ee-ada5-da3d9ad34c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='排列5'])[1]/preceding::a[4]</value>
      <webElementGuid>143a71b5-260c-4cf3-a203-8bae1b1250e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PK10']/parent::*</value>
      <webElementGuid>93586d9e-4ae5-42eb-8c41-40f97245fa70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[2]</value>
      <webElementGuid>99087739-ff16-4e15-a4d3-e18ef9295d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>8ba04d98-e95d-48ba-9d36-e08cb508391f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ig_inlet_pk' and @href = 'javascript:void(0);' and (text() = 'PK10' or . = 'PK10')]</value>
      <webElementGuid>47a5883d-e8a9-472b-8044-5a8be560d553</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
