<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_115</name>
   <tag></tag>
   <elementGuidId>58310697-a125-4822-aadf-60c5d7bcde7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li[name='GD115'] a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'11选5')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;11选5&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06f954b9-bd1a-4b68-8fde-2a21a7280323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>34d470d8-0bb5-42f6-bf6b-a85dabd98cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11选5</value>
      <webElementGuid>b3d10561-7c89-4a4d-a9c8-5c0ba05aa332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBody&quot;)/div[@class=&quot;gfcMainPage&quot;]/div[@class=&quot;top_content&quot;]/ul[@class=&quot;title-menu&quot;]/li[@class=&quot;biankuang bg_color1&quot;]/a[1]</value>
      <webElementGuid>862c55e6-a2c2-4f88-8d34-985e7310c232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='mainBody']/div/div/ul/li[4]/a</value>
      <webElementGuid>7d12a314-7dae-484c-9883-cb53f9b466f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'11选5')]</value>
      <webElementGuid>e44e8c2a-1bcf-4032-a9dc-199b1df482c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='时时彩'])[1]/following::a[1]</value>
      <webElementGuid>3c9a0ce6-d2ce-4e22-af29-c90c0542dd32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PK10'])[1]/following::a[2]</value>
      <webElementGuid>d4842249-b567-425a-b57a-6230482f93f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='排列5'])[1]/preceding::a[2]</value>
      <webElementGuid>37a05176-aa02-4f9c-a5dc-33558eb6e9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='快3'])[1]/preceding::a[3]</value>
      <webElementGuid>d3ef44bf-5afe-4729-8544-49645b654b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='11选5']/parent::*</value>
      <webElementGuid>63911611-bf26-4add-9ee4-7281bd9ebb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[4]</value>
      <webElementGuid>2d46de12-d34f-4d04-b45c-7bb3387e4fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>7486c2d6-adf7-4265-a7ba-0f2a1b95e196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '11选5' or . = '11选5')]</value>
      <webElementGuid>b9e0db86-5b39-43dd-94f4-143749660f3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
