<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_DirectBetting</name>
   <tag></tag>
   <elementGuidId>63789557-fe47-420a-9630-3326b9a84d0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.directBet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'直接投注')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;直接投注&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>89320cf6-cf34-49bc-b280-562f5f9d9af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>7d5e26e5-33e0-43dd-8ec9-884cba959afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>directBet</value>
      <webElementGuid>ab11ce66-6ce4-416b-8155-95ee53a1e4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>直接投注</value>
      <webElementGuid>47016e56-014c-4881-8671-88adc2d85cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click:directBet</value>
      <webElementGuid>33955cb1-bb8c-4bca-a19a-b68a4cb142e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>直接投注</value>
      <webElementGuid>312dcb42-3992-4857-a69e-2a37e167a2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBody&quot;)/div[@class=&quot;gfcMainPage&quot;]/div[@class=&quot;main_content&quot;]/div[@class=&quot;center_content&quot;]/div[@class=&quot;betSet&quot;]/a[@class=&quot;directBet&quot;]</value>
      <webElementGuid>2f7ba50f-d255-480d-aabc-21c4bdec64bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='mainBody']/div/div[2]/div[3]/div[3]/a</value>
      <webElementGuid>7095c670-b808-4ea9-a8d3-2d308a514000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'直接投注')]</value>
      <webElementGuid>660f6a0d-ed08-4674-8abf-40bb699ecb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='加入号码篮'])[1]/preceding::a[1]</value>
      <webElementGuid>269ca218-46b0-45d9-a979-7bb17e5764ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::a[2]</value>
      <webElementGuid>f98de0f8-9941-450e-9631-72f0c267352c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='直接投注']/parent::*</value>
      <webElementGuid>d655eabd-61e5-420c-b5be-9ed323408791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[77]</value>
      <webElementGuid>db1c5aeb-79b2-47bb-9d9f-198e81514eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>c05775b9-2c6a-436a-ad62-5d6ad8222384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @title = '直接投注' and (text() = '直接投注' or . = '直接投注')]</value>
      <webElementGuid>87b722e3-3522-41f1-beff-cf200195397e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
