<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_COLORFUL</name>
   <tag></tag>
   <elementGuidId>17978cd4-b736-478c-b629-c0dc6c2899f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.addBasket</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'时时彩')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;加入号码篮&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96e8bf93-6667-4fa4-b4ea-2de00f298e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>074747af-301a-48ff-88a2-865c7e50a343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addBasket</value>
      <webElementGuid>cfc239a0-bcd6-4b3a-acaf-82b965fa23e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>加入号码篮</value>
      <webElementGuid>a9ba83ea-ecf9-4aad-b1f4-7bfe3e1ec8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click:$parent.betBagViewModel.addBetBag</value>
      <webElementGuid>d68afd0d-530d-4c76-bef4-da9cc4f15a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>加入号码篮</value>
      <webElementGuid>bc59ea1f-15ef-466c-9297-b48b45cbd47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBody&quot;)/div[@class=&quot;gfcMainPage&quot;]/div[@class=&quot;main_content&quot;]/div[@class=&quot;center_content&quot;]/div[@class=&quot;betSet&quot;]/a[@class=&quot;addBasket&quot;]</value>
      <webElementGuid>f41e6198-e684-448e-8799-a398e60366b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='mainBody']/div/div[2]/div[3]/div[3]/a[2]</value>
      <webElementGuid>d3d010f7-5def-4cb1-a141-46c335a8a189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'加入号码篮')]</value>
      <webElementGuid>a6afdf79-c9ca-4419-a73d-586660232ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='直接投注'])[1]/following::a[1]</value>
      <webElementGuid>a5056ccf-56de-4e66-a0b6-372e5fada530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::a[1]</value>
      <webElementGuid>4ae3b4ef-62dc-4d3c-a73a-1d288f25b6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全加减1倍'])[1]/preceding::a[2]</value>
      <webElementGuid>506c0ae3-d2c8-447a-89d5-39d18c8710c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='加入号码篮']/parent::*</value>
      <webElementGuid>773ad4a3-7378-43a0-8a44-8c49bb8b12f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[78]</value>
      <webElementGuid>2977d85a-146a-41cf-b76f-61774e6c5af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a[2]</value>
      <webElementGuid>c944163d-d35c-4a96-a2bb-f7bb1dc26908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @title = '加入号码篮' and (text() = '加入号码篮' or . = '加入号码篮')]</value>
      <webElementGuid>cc63adc5-e748-422f-84fb-ae42c494b6c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
