<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_Confirm</name>
   <tag></tag>
   <elementGuidId>f5dea47b-6b2c-436f-8958-60f0c2c05947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.directBet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'确定')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;直接投注&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ec92a75-42f9-4004-8847-fb472d4ae4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>748846fc-66dc-45ed-b0f7-2e0b53fb2a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>directBet</value>
      <webElementGuid>56560a7e-15c1-4951-93d5-6820ed86576a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>直接投注</value>
      <webElementGuid>8a4577ba-8abb-473a-b18b-920c562a8fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click:directBet</value>
      <webElementGuid>147703e0-ace6-4d22-8826-9971bb6ede07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>直接投注</value>
      <webElementGuid>4581e26b-608d-4dce-a4b8-0a5395b7a492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBody&quot;)/div[@class=&quot;gfcMainPage&quot;]/div[@class=&quot;main_content&quot;]/div[@class=&quot;center_content&quot;]/div[@class=&quot;betSet&quot;]/a[@class=&quot;directBet&quot;]</value>
      <webElementGuid>250fc094-ecbe-43bb-a3bb-96c11ac2e350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='mainBody']/div/div[2]/div[3]/div[3]/a</value>
      <webElementGuid>a89d0f97-d8e6-4098-81f2-44c7795e7e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'直接投注')]</value>
      <webElementGuid>e0468a0c-4235-40e3-a83e-a347984244fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='加入号码篮'])[1]/preceding::a[1]</value>
      <webElementGuid>c2fee7c0-9139-411c-8955-8f1d5f3bc176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::a[2]</value>
      <webElementGuid>d7e7bbc3-e0df-464a-88dd-2926f2ce24a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='直接投注']/parent::*</value>
      <webElementGuid>03df2df0-d825-4e62-b3f9-0c63a190a743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[77]</value>
      <webElementGuid>088fefa5-3b31-422a-8b07-85016b803191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>2981e65a-7ccb-4dd4-bf39-4d22311ad0c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @title = '直接投注' and (text() = '直接投注' or . = '直接投注')]</value>
      <webElementGuid>bf99b47b-f788-48e0-866e-57d88196477c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
