<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_3D</name>
   <tag></tag>
   <elementGuidId>75dc7f6a-5bd7-4f18-bcd3-619511ac47a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li[name=&quot;FC3D&quot;] > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[normalize-space()='3D']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;3D&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb1d5af2-0bee-40d2-81d2-54d6cc77ac85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>37530617-a416-4427-9fc3-75890ac9d31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3D</value>
      <webElementGuid>94709885-c53d-4e05-8b5c-7663967045e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBody&quot;)/div[@class=&quot;gfcMainPage&quot;]/div[@class=&quot;top_content&quot;]/ul[@class=&quot;title-menu&quot;]/li[@class=&quot;biankuang bg_color1&quot;]/a[1]</value>
      <webElementGuid>62d33520-86f9-42c0-9e14-d76a587618fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='mainBody']/div/div/ul/li[5]/a</value>
      <webElementGuid>6cf152f1-f400-4ebe-8076-677627faebfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'3D')]</value>
      <webElementGuid>2b11ed33-3edd-4ff5-a9a9-f1eb86213f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='时时彩'])[1]/following::a[2]</value>
      <webElementGuid>b6c250a2-c7ae-48ee-9462-da478b6570b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PK10'])[1]/following::a[3]</value>
      <webElementGuid>33419550-e0ef-497c-aa85-b8367ff9354a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='排列5'])[1]/preceding::a[1]</value>
      <webElementGuid>7f506c31-59c5-492b-ae31-0b46cfa7f616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='快3'])[1]/preceding::a[2]</value>
      <webElementGuid>f176b3b8-7f0f-4caa-b6bd-49dd7a4c1aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3D']/parent::*</value>
      <webElementGuid>7d3412c8-6f03-42e1-8283-4afc77774d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[5]</value>
      <webElementGuid>1e3baaf0-cbe8-427c-8511-2252145f0add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>fa9b2db8-5e80-4c71-a00c-1c3e9f94fcbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '3D' or . = '3D')]</value>
      <webElementGuid>17d37851-8b17-4183-93a8-c887c9e6cf7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
