<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Tianyou</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>357a2fce-093e-402e-aac9-aed616b11395</testSuiteGuid>
   <testCaseLink>
      <guid>e9ef10f3-d64c-44fd-a81d-6ad3b9d4b546</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Execution/IMONE BOARDGAMES/Tianyou Gaming/NewLaunchGame</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8a53edcf-31e4-42e4-bcb9-55b1a7979469</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Execution/IMONE BOARDGAMES/Tianyou Gaming/GetBalance</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9a92768f-2353-4fc4-8c05-0d0267905df8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Execution/IMONE BOARDGAMES/Tianyou Gaming/NewLaunchMobileGame</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5552c96e-84f5-4615-b1fe-b812277192c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Execution/IMONE BOARDGAMES/Tianyou Gaming/Player</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>210416da-6b77-4c9b-abb5-9a47d76da380</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Execution/IMONE BOARDGAMES/Tianyou Gaming/Perform Transfer</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>162df266-a8bc-4422-ada4-75bf7892d0db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41cea837-2f7a-4662-83fe-95333faeca70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0e3ebf5-f773-4d0b-a6ac-0de2a8b3db2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06832aeb-014a-4fb3-849d-0e43aca1a583</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71d8eadc-0b83-4c5b-a752-3591ad0a8dda</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60c184cb-f7bd-4306-b0d8-fe5cabc3e53c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Execution/IMONE BOARDGAMES/Tianyou Gaming/Check Transfer Status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>162df266-a8bc-4422-ada4-75bf7892d0db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41cea837-2f7a-4662-83fe-95333faeca70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0e3ebf5-f773-4d0b-a6ac-0de2a8b3db2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06832aeb-014a-4fb3-849d-0e43aca1a583</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71d8eadc-0b83-4c5b-a752-3591ad0a8dda</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
