<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Help_stage</name>
   <tag></tag>
   <elementGuidId>71310c20-7fbd-4f45-9a85-f5afcffae86f</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='stage']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'stage' and @ref_element = 'Object Repository/Execution/IMONE SLOT/RedTiger/Red Tiger Casino/iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#stage</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>57513a4a-bf80-4b77-9eb1-f90862d58922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1280</value>
      <webElementGuid>def6baaf-75e1-41e6-b7d9-ebac3be81ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>720</value>
      <webElementGuid>a824fedc-2272-4ea9-98f3-d524386ad870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stage</value>
      <webElementGuid>30686c90-c915-43e1-83f3-b359c4042e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stage&quot;)</value>
      <webElementGuid>09f7abc6-499c-441d-9a60-eb4177dc6983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Execution/IMONE SLOT/RedTiger/Red Tiger Casino/iframe (1)</value>
      <webElementGuid>67c159f3-d5ae-419b-aafe-53eb6dc3504a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='stage']</value>
      <webElementGuid>26e725a5-0345-43c9-bfcb-498fb41cbfb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='game']/div/canvas</value>
      <webElementGuid>31155cbf-939c-4e3a-a7cc-dd44950f91cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>10a853bb-f901-4e3d-bbe6-c6764214b401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'stage']</value>
      <webElementGuid>4df18452-592f-4f96-b490-fa66f39950fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
