<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Stop Auto Spin_on any win</name>
   <tag></tag>
   <elementGuidId>63e7e0f2-75d6-41f1-a0c3-3c5c434698bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='controlbarH5']/div/div[4]/div[2]/div[2]/div[2]/div[3]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.select_box > span.select_checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>048611a7-d3f9-4350-819a-3b36d94c40b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_checkbox</value>
      <webElementGuid>647543bc-5fd7-4e83-8704-18c12d9cf159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;controlbarH5&quot;)/div[@class=&quot;controlbarChild&quot;]/div[@class=&quot;controlbar_new_web&quot;]/div[@class=&quot;autospin_web active&quot;]/div[@class=&quot;autospin_main&quot;]/div[@class=&quot;autospin_web_center&quot;]/div[@class=&quot;autospin_select&quot;]/div[@class=&quot;select_box&quot;]/span[@class=&quot;select_checkbox&quot;]</value>
      <webElementGuid>8845f0e2-8809-4863-96f8-dbad117d4128</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='controlbarH5']/div/div[4]/div[2]/div[2]/div[2]/div[3]/div/span</value>
      <webElementGuid>c8f6c64d-7388-4624-92ab-141dabda6343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stop Auto Spin'])[1]/following::span[1]</value>
      <webElementGuid>1de19eef-765c-46b7-a4e9-a18253dd17ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPIN WITHOUT REELS'])[1]/following::span[1]</value>
      <webElementGuid>a9a81f17-6ed7-43eb-a779-809344e1efe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If single win exceeds'])[1]/preceding::span[3]</value>
      <webElementGuid>976c709f-a1ab-43fe-aeee-459b6fc0f9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[1]/preceding::span[4]</value>
      <webElementGuid>5b281db9-92aa-4271-b7e5-0966fa553497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/span</value>
      <webElementGuid>5f55174a-54f4-459d-af57-6009876e11e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
