<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_25</name>
   <tag></tag>
   <elementGuidId>ac106231-88e5-48fc-928d-3aa0e19ce9d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.autoSpinLeftTimes</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '25' or . = '25')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = '25' or . = '25')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3bce9ca2-d50e-4c52-a6b8-367e127b0bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autoSpinLeftTimes</value>
      <webElementGuid>0083f168-b093-4b07-8fbc-5d21379e142b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>bcc2dd06-9200-4127-b834-bc73e4a01cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gameControlPanel&quot;)/div[@class=&quot;control-panel-container&quot;]/div[@class=&quot;operation-section&quot;]/div[@class=&quot;operation-wrapper&quot;]/div[@class=&quot;button-spin&quot;]/span[@class=&quot;autoSpinLeftTimes&quot;]</value>
      <webElementGuid>92ccc333-8ae3-4792-94ff-06f6f6861fde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gameControlPanel']/div/div[3]/div/div[3]/span</value>
      <webElementGuid>2323cdd3-a8a7-47f7-b1db-91dfa9dbcaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥ 0.5'])[1]/following::span[1]</value>
      <webElementGuid>f3cb2f55-3c08-472a-a92a-23d4ec9cac66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥ 19,522.62'])[1]/following::span[2]</value>
      <webElementGuid>51fa1fe5-dceb-43da-808f-0309154c6dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.5250261575705'])[1]/preceding::span[1]</value>
      <webElementGuid>91fc8df7-7689-43ac-a5c4-6edab23edc70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LINE(S) 50'])[1]/preceding::span[1]</value>
      <webElementGuid>f88680ba-fbdd-41f6-ac7d-998f10022bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='25']/parent::*</value>
      <webElementGuid>e8abcbfe-7114-4463-bc9f-05103818e0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>f5498a04-3585-455d-bb79-c1779fa86c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '25' or . = '25')]</value>
      <webElementGuid>6b6603a2-5164-44df-b764-d96908846a8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
