<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_50</name>
   <tag></tag>
   <elementGuidId>84e61a0a-59c4-4fb0-839c-4da3daa58a4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.autoSpinLeftTimes</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '50' or . = '50')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = '50' or . = '50')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>32e75acd-8baa-4810-bbaf-aadb1f0a0f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autoSpinLeftTimes</value>
      <webElementGuid>6f568afc-1e69-4ee4-a94d-d3755620637d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f43cf1bb-3ea0-4871-9c31-d36018886346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gameControlPanel&quot;)/div[@class=&quot;control-panel-container&quot;]/div[@class=&quot;operation-section&quot;]/div[@class=&quot;operation-wrapper&quot;]/div[@class=&quot;button-spin&quot;]/span[@class=&quot;autoSpinLeftTimes&quot;]</value>
      <webElementGuid>fd29a2eb-8d89-457e-b0a1-9dd963f066e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gameControlPanel']/div/div[3]/div/div[3]/span</value>
      <webElementGuid>add0703a-e804-4feb-afa7-cb0885764cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥ 0.5'])[1]/following::span[1]</value>
      <webElementGuid>b12d96b9-13dc-4597-b99a-f89ea9b5af55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥ 19,522.62'])[1]/following::span[2]</value>
      <webElementGuid>8ff9af78-3ba1-4784-b91a-26027a80f013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.5250261575705'])[1]/preceding::span[1]</value>
      <webElementGuid>f3ff3824-5ba1-4756-b4c3-e5ff1e76a378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LINE(S) 50'])[1]/preceding::span[1]</value>
      <webElementGuid>19de77ba-14c3-4452-aad4-7cc6b8841b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='50']/parent::*</value>
      <webElementGuid>c35934b3-5eea-4bab-a24a-d420a7754959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>e0043c0a-232f-4797-b074-6ad6acf3de06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '50' or . = '50')]</value>
      <webElementGuid>ee2ad338-6ad2-4ec1-ad65-f0de6a5aea47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
