<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_15</name>
   <tag></tag>
   <elementGuidId>3eef52e3-5b5c-4285-add4-e50f8f148a1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.autoSpinLeftTimes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = '15' or . = '15')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2764b46d-2f52-45ab-9805-74973ea3b9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autoSpinLeftTimes</value>
      <webElementGuid>e7261ef5-991a-410b-b52b-34e09452a546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>42208233-8494-4d63-bac1-9dbea0ab74e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gameControlPanel&quot;)/div[@class=&quot;control-panel-container&quot;]/div[@class=&quot;operation-section&quot;]/div[@class=&quot;operation-wrapper&quot;]/div[@class=&quot;button-spin&quot;]/span[@class=&quot;autoSpinLeftTimes&quot;]</value>
      <webElementGuid>8e12f67f-7c0d-46f1-a704-dfba060d49ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gameControlPanel']/div/div[3]/div/div[3]/span</value>
      <webElementGuid>1b3f3dd0-6f25-4be3-a62a-b939bfcc54dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥ 0.5'])[1]/following::span[1]</value>
      <webElementGuid>c70c23dd-eb0c-465b-852b-b0abab0bcf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥ 19,522.62'])[1]/following::span[2]</value>
      <webElementGuid>3f730bea-74ed-4fbd-91a7-9e709ec42468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.5250261575705'])[1]/preceding::span[1]</value>
      <webElementGuid>a1c9bdce-7461-4e57-b92f-1790eae6a913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LINE(S) 50'])[1]/preceding::span[1]</value>
      <webElementGuid>5f70462f-4e81-4f57-b64a-0184a0ce3de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='15']/parent::*</value>
      <webElementGuid>54a574d5-0460-4541-b326-9f3a598d1186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>bd2b108e-fa96-4fa6-b2c6-16475dfcef68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '15' or . = '15')]</value>
      <webElementGuid>e7611025-247a-4f6f-afc1-ff3e20dd9fb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
