<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_150</name>
   <tag></tag>
   <elementGuidId>50948ac0-9ca3-4ac6-b789-778d37022aae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.autoSpinLeftTimes</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '150' or . = '150')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = '150' or . = '150')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>02c07960-7ebe-4fb0-9de2-5a4c5498343c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autoSpinLeftTimes</value>
      <webElementGuid>a4475ca9-ba4e-42a7-af3a-534afd64b82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>44e78ddc-cbf0-4597-b9d7-e329f0e8d989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gameControlPanel&quot;)/div[@class=&quot;control-panel-container&quot;]/div[@class=&quot;operation-section&quot;]/div[@class=&quot;operation-wrapper&quot;]/div[@class=&quot;button-spin&quot;]/span[@class=&quot;autoSpinLeftTimes&quot;]</value>
      <webElementGuid>03345e10-6cad-4f24-b9ca-999ece7d4f5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gameControlPanel']/div/div[3]/div/div[3]/span</value>
      <webElementGuid>b240b55d-9fb1-4a54-b62d-973fb96e80f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥ 0.5'])[1]/following::span[1]</value>
      <webElementGuid>a29515d7-13b1-4c7d-94e8-8d2e0e5ed43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥ 19,522.62'])[1]/following::span[2]</value>
      <webElementGuid>c2770fee-7fc2-40a4-b96b-d548c2d5b396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.5250261575705'])[1]/preceding::span[1]</value>
      <webElementGuid>ab22a98c-b57d-450b-946c-1b43d85ea282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LINE(S) 50'])[1]/preceding::span[1]</value>
      <webElementGuid>2bc213d7-09bc-4c39-a0bb-157414765acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='150']/parent::*</value>
      <webElementGuid>139f359a-e775-489b-bf07-09e7a60d404c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>8d123f55-fb1c-4dd3-9637-4e8c292c186b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '150' or . = '150')]</value>
      <webElementGuid>6fac7709-2359-47c5-8859-de109c720cfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
