<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ADVANCED</name>
   <tag></tag>
   <elementGuidId>70da0c78-71de-4842-9ec8-0a697469d505</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AutoplayAdvancedToggle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AutoplayAdvancedToggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AutoplayAdvancedToggle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90e18186-2628-4e31-9289-6eb9b5671e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AutoplayAdvancedToggle</value>
      <webElementGuid>535c32ef-fd7e-40d9-9dc5-c9ed1b9bc2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Menu-advance-toggle</value>
      <webElementGuid>18170518-e603-4921-9fea-3924360ed93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>AdvancedAutoplaySections</value>
      <webElementGuid>b8eba0b1-ace0-4255-a33f-5e8772d06e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADVANCED</value>
      <webElementGuid>7db6ac0e-db0d-4c7d-940a-e50a0cab8681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AutoplayAdvancedToggle&quot;)</value>
      <webElementGuid>e4970b34-de3b-4391-a9d8-387e05ef1b6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='AutoplayAdvancedToggle']</value>
      <webElementGuid>00f42e7f-fc94-494a-a6a3-2b4022cbe89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AutoplayNav']/div</value>
      <webElementGuid>82021127-3b64-40ad-a540-f0ec1a37dfa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥10.00'])[3]/following::div[2]</value>
      <webElementGuid>a0b56280-c40d-43ba-8768-260b78125daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BET'])[4]/following::div[2]</value>
      <webElementGuid>6b5c9e6e-d30c-4a3c-8e4b-6218a944a93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUTOPLAY'])[1]/preceding::div[1]</value>
      <webElementGuid>cdf72d04-5348-41c0-a9f8-2d0906413505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div</value>
      <webElementGuid>a1259eb9-6b61-4c21-b316-dba53ec5b971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'AutoplayAdvancedToggle' and (text() = 'ADVANCED' or . = 'ADVANCED')]</value>
      <webElementGuid>d352e813-70d0-4e00-84fa-5c8e48b95ff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
