<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Toggle_StopOnFeatureWin</name>
   <tag></tag>
   <elementGuidId>83bf5ebb-4f71-4fa3-8e8e-8a7d882d5267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='StopOnFeatureSection']/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.Toggle--label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Toggle&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cce093d5-63cf-4f93-afd8-251aaf9d4669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>StopOnFeatureToggle</value>
      <webElementGuid>da69c4c0-c705-4c3f-9d64-2c468f3e0c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toggle--label</value>
      <webElementGuid>819d265f-85b9-4347-8f71-3dc72dad1aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toggle</value>
      <webElementGuid>8e1eaaeb-ed78-4150-8f42-25a7255dabc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StopOnFeatureSection&quot;)/div[@class=&quot;Toggle&quot;]/label[@class=&quot;Toggle--label&quot;]</value>
      <webElementGuid>e89ef85d-ee41-4a3f-8a7e-87447892a019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='StopOnFeatureSection']/div[2]/label</value>
      <webElementGuid>40ce3014-66c1-41e0-87b5-1f30362f63d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STOP ON SPECIAL FEATURE WIN'])[1]/following::label[1]</value>
      <webElementGuid>3804761b-3f88-41ae-a728-20ce7f280ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NUMBER OF ROUNDS'])[1]/following::label[1]</value>
      <webElementGuid>e1c06cf1-da25-440f-aca0-d558993ead24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOSS LIMIT'])[1]/preceding::label[1]</value>
      <webElementGuid>006edaa0-d439-410b-898d-3f893556b04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO LIMIT'])[1]/preceding::label[1]</value>
      <webElementGuid>8cb0dd10-e229-4c29-9b50-c0781615e0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Toggle']/parent::*</value>
      <webElementGuid>d3f539f9-70d7-4f27-b60e-509bdcd2797a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>a948a909-271b-430e-9a4a-53905c8bce75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Toggle' or . = 'Toggle')]</value>
      <webElementGuid>37448278-719a-4397-afce-ef53d12a4363</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
