<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SSC(Trad.)</name>
   <tag></tag>
   <elementGuidId>91e8d403-ca16-43d4-b40e-c1c8d28554bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.menu-container > ul.u_clearfix > li.is_active.us > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[normalize-space()='SSC(Trad.)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;SSC(Trad.)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3e6e97a-17f7-4575-92ba-061def241f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SSC(Trad.)</value>
      <webElementGuid>e2dab5f6-705b-493d-a975-5aa4f37aa26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;desktop&quot;]/body[1]/div[@class=&quot;lang_us&quot;]/div[1]/div[1]/div[@class=&quot;gr_header u_clearfix&quot;]/div[@class=&quot;gr_nav--nav-bar&quot;]/div[@class=&quot;gr_nav__dropdown  c_dropdown gr_nav__dropdown--hover  c_dropdown--hover&quot;]/div[@class=&quot;c_dropdown-box--list-box-new&quot;]/div[@class=&quot;container&quot;]/div[2]/div[@class=&quot;menu-container&quot;]/ul[@class=&quot;u_clearfix&quot;]/li[@class=&quot;is_active us&quot;]/div[1]</value>
      <webElementGuid>de5a6bf5-dd9b-4102-a2ad-94dcc14ef4d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose lottery'])[1]/following::div[2]</value>
      <webElementGuid>f57c26e1-2a72-40af-bfed-514da7960d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia Lottery'])[1]/following::div[4]</value>
      <webElementGuid>ce3b5cdd-5250-4d62-ab4d-16ae83f484fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fast 3(Trad.)'])[1]/preceding::div[2]</value>
      <webElementGuid>f69128ad-0c6d-4b79-9f49-3b3b7233bf64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PK10(Trad.)'])[1]/preceding::div[3]</value>
      <webElementGuid>4051d519-1539-4305-a013-bb14b1dd827f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SSC(Trad.)']/parent::*</value>
      <webElementGuid>b964e7f7-7701-40e1-abf5-bd9ebf75805e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/div</value>
      <webElementGuid>31af6107-fc20-418f-8620-e28a6299a50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'SSC(Trad.)' or . = 'SSC(Trad.)')]</value>
      <webElementGuid>ec91901f-caaa-4b25-b401-7d6ed903f8f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
