<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bottom</name>
   <tag></tag>
   <elementGuidId>71078ba1-6f95-442d-add3-3026d43f3894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='tel'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) > .gr_title__input > .c_input__inner</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fd57e62-521e-4a81-82b8-5b59c9a9d1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>be3b61e5-ff40-4345-9bad-d7acf2870799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c_input__inner</value>
      <webElementGuid>4ace0b78-9ecb-4671-a5f1-3dd812cf040e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;desktop&quot;]/body[1]/div[@class=&quot;lang_us&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;gr_container bg_primary u_p--r10 u_p--l10&quot;]/div[@class=&quot;gr_grid-vn&quot;]/div[@class=&quot;gr_row&quot;]/div[@class=&quot;gr_col&quot;]/div[@class=&quot;gr_row gr_grid-vn__title&quot;]/div[@class=&quot;gr_component&quot;]/div[@class=&quot;gr_title__input c_input--short&quot;]/input[@class=&quot;c_input__inner&quot;]</value>
      <webElementGuid>8efc1fcb-103f-4660-a093-0bd6830c6fab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='tel'])[2]</value>
      <webElementGuid>e9434496-6571-4311-9f50-10878b6d129d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d4eb52a7-91ad-4319-af0b-30ccd29df611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>ada8884b-0226-4961-81a4-511f302adc97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
