<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TopBottom</name>
   <tag></tag>
   <elementGuidId>91bbd540-4f02-4766-bf6d-1de6d6e9cd08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='tel'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(3) > .gr_title__input > .c_input__inner</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e4ecb78-093e-4376-b51b-99d81190fb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>bb23e574-d9a8-462a-b528-7a923dc8ad67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c_input__inner</value>
      <webElementGuid>f894121c-fa40-4ecd-9369-0ca06555b994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;desktop&quot;]/body[1]/div[@class=&quot;lang_us&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;gr_container bg_primary u_p--r10 u_p--l10&quot;]/div[@class=&quot;gr_grid-vn&quot;]/div[@class=&quot;gr_row&quot;]/div[@class=&quot;gr_col&quot;]/div[@class=&quot;gr_row gr_grid-vn__title&quot;]/div[@class=&quot;gr_component&quot;]/div[@class=&quot;gr_title__input c_input--short&quot;]/input[@class=&quot;c_input__inner&quot;]</value>
      <webElementGuid>81689174-c38c-4faa-bad1-d97bbb9b26b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='tel'])[3]</value>
      <webElementGuid>d7f6aa6c-fc1c-41bf-9c26-9cdaf441f5a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>4315a63d-7776-4582-8540-8fbcc898820b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>7b7695e5-f56d-4b19-a294-abe2bd3bb20e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
