<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Roll</name>
   <tag></tag>
   <elementGuidId>5e1a07ec-e3b1-4df7-a2ce-abe6a00c3ffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='tel'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(4) > .gr_title__input > .c_input__inner</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac4f076c-583e-4a99-9fba-7313bcf4fa7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2a1ecb85-d21e-4d1c-9b09-e1cf7c587326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c_input__inner</value>
      <webElementGuid>8fc6aa2d-4052-4661-a557-f7de455bbade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;desktop&quot;]/body[1]/div[@class=&quot;lang_us&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;gr_container bg_primary u_p--r10 u_p--l10&quot;]/div[@class=&quot;gr_grid-vn&quot;]/div[@class=&quot;gr_row&quot;]/div[@class=&quot;gr_col&quot;]/div[@class=&quot;gr_row gr_grid-vn__title&quot;]/div[@class=&quot;gr_component&quot;]/div[@class=&quot;gr_title__input c_input--short&quot;]/input[@class=&quot;c_input__inner&quot;]</value>
      <webElementGuid>ea66fde9-0d8b-407e-baaa-bf297562090d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='tel'])[4]</value>
      <webElementGuid>31deb0e2-80a8-41c3-a2e6-9beb81eb7ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>22a24ed6-ce3b-46d6-bb91-8d835075d7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>6792c5d4-715d-468c-948e-38a07ea022bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
