<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Top</name>
   <tag></tag>
   <elementGuidId>bfbb63b9-e7f1-496c-b2d8-ecaaae7e7fdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.c_input__inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='tel'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.c_input__inner >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6aed045-3444-46c1-beb4-d00d1b29be85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>e97d82cd-7cb4-43b5-a90a-f06ed73d2b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c_input__inner</value>
      <webElementGuid>8b2f9921-8d47-460c-b070-065a59744494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;desktop&quot;]/body[1]/div[@class=&quot;lang_us&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;gr_container bg_primary u_p--r10 u_p--l10&quot;]/div[@class=&quot;gr_grid-vn&quot;]/div[@class=&quot;gr_row&quot;]/div[@class=&quot;gr_col&quot;]/div[@class=&quot;gr_row gr_grid-vn__title&quot;]/div[@class=&quot;gr_component&quot;]/div[@class=&quot;gr_title__input c_input--short&quot;]/input[@class=&quot;c_input__inner&quot;]</value>
      <webElementGuid>a446b6be-2ed7-45cb-9197-08f25ef55488</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='tel']</value>
      <webElementGuid>93691abc-bf28-4ff5-9dd7-6dce823d2175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bcb2a736-8f70-439a-b7cc-f328d8bee8f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>d5f73554-d752-472d-850a-87aae7af7ecc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
