<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>World Entertainment (EBET)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>20fc281e-f040-4ee2-ac79-61b8580bcc0c</testSuiteGuid>
   <testCaseLink>
      <guid>df0e1dd3-67c0-45a5-b6ff-a280b27f5823</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Execution/IMONE LIVE DEALER/World Entertainment (EBET)/GetBalance</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7e89d253-3cbc-4776-b8f8-2782ddd1b357</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Execution/IMONE LIVE DEALER/World Entertainment (EBET)/NewLaunchMobileGame</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>aa6822f8-39a8-4e85-a82f-c9a47d65e60a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Execution/IMONE LIVE DEALER/World Entertainment (EBET)/Player</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b090b90c-3882-4c81-96a1-e7da409eec75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Execution/IMONE LIVE DEALER/World Entertainment (EBET)/Perform Transfer</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>131c1ed8-a0a2-45da-bc20-c979ccae7f7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6a81eb8-b5c3-44be-9c48-25b766432d26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a86b9f9d-1efc-4d62-837c-bd3230853a48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52c28b99-4c3e-4ed3-8662-41566f3c2f5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d2e84c5-7467-4b03-916f-6de8c3f81edc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b735ca5-371f-4a5b-8c7a-7e46151aff7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Execution/IMONE LIVE DEALER/World Entertainment (EBET)/Check Transfer Status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>131c1ed8-a0a2-45da-bc20-c979ccae7f7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6a81eb8-b5c3-44be-9c48-25b766432d26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a86b9f9d-1efc-4d62-837c-bd3230853a48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52c28b99-4c3e-4ed3-8662-41566f3c2f5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d2e84c5-7467-4b03-916f-6de8c3f81edc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
