<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_chip100</name>
   <tag></tag>
   <elementGuidId>4b294bcc-c6cd-4c04-b81c-c1f2778fb335</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.gr_game-controller__money.is_active > div.gr_money__chip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'gr_money__chip')][normalize-space()='100']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;100&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf86430e-d1b8-4c06-aaaf-4c80f6c5763b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gr_money__chip</value>
      <webElementGuid>e66f8d27-f24d-47c6-acd5-abef254144e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                100
            </value>
      <webElementGuid>dad78347-769a-45b5-92a7-89abc47ab320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;desktop&quot;]/body[1]/div[@class=&quot;lang_us&quot;]/div[1]/div[1]/div[2]/div[3]/div[@class=&quot;gr_game-controller--fantan  gr_container  bg_primary  u_inline-field  u_clearfix&quot;]/div[2]/div[@class=&quot;gr_game-controller__money is_active&quot;]/div[@class=&quot;gr_money__chip&quot;]</value>
      <webElementGuid>a0772570-33af-42d4-8eda-725e833a3124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/following::div[9]</value>
      <webElementGuid>c0866396-f9f9-4628-8ab7-97d507ec3f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Even'])[1]/following::div[117]</value>
      <webElementGuid>1b216693-14ec-4210-b11f-ab3d4c6d3ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/preceding::div[9]</value>
      <webElementGuid>5d11eb6c-43a2-4ea9-a774-dcb7e6e80bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::div[10]</value>
      <webElementGuid>395e376d-51db-4d57-ba7a-c9129f5b53bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='100']/parent::*</value>
      <webElementGuid>8e5d2679-5656-40d4-bae7-f9ed32412ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[4]/div</value>
      <webElementGuid>2b6a3a89-75ac-479d-b16a-5972f4b02584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                100
            ' or . = '
                100
            ')]</value>
      <webElementGuid>a7498a34-dc71-4c56-83aa-8408db739b27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
