<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bttn_add_over</name>
   <tag></tag>
   <elementGuidId>15f435ca-0a18-4f34-ad90-917ef02cc141</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.bgimgStyle.bttn_add_over</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='controlbarH5']/div/div[4]/div/div/div/div[2]/div/div[6]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f4b387cf-22a5-495a-9922-106bee95c433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bttn_add</value>
      <webElementGuid>a21d82df-f768-41ff-9a8e-b6eb607434d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bgimgStyle bttn_add_over</value>
      <webElementGuid>ac9b15ae-06eb-4209-8355-bdf9aa510a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>18f676da-d3a2-449e-b621-e3412a71774e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unclick</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9d95b6ff-e258-4552-a8d7-21c92f448f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;controlbarH5&quot;)/div[@class=&quot;controlbarChild&quot;]/div[@class=&quot;controlbar_new_web&quot;]/div[@class=&quot;controlbarMain&quot;]/div[@class=&quot;controlbar_top clearfix&quot;]/div[@class=&quot;controlbar_top_main&quot;]/div[@class=&quot;l_betInfo fl&quot;]/div[@class=&quot;info_box&quot;]/div[@class=&quot;box_add l_gameBet_add&quot;]/span[@class=&quot;bgimgStyle bttn_add_over&quot;]</value>
      <webElementGuid>8827c4b3-11ed-4b39-897c-97a5acfde047</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='controlbarH5']/div/div[4]/div/div/div/div[2]/div/div[6]/span</value>
      <webElementGuid>afb78706-ae74-47dc-bccd-f19bd891ba63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div[6]/span</value>
      <webElementGuid>6c43fc2e-ae7e-438e-b033-4754e4dc4ef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
