<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bttn_minus_over</name>
   <tag></tag>
   <elementGuidId>d4a8a382-6d6f-4f5b-ba8e-1f633f3e7e32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.bgimgStyle.bttn_minus_over</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;controlbarH5&quot;)/div[@class=&quot;controlbarChild&quot;]/div[@class=&quot;controlbar_new_web&quot;]/div[@class=&quot;controlbarMain&quot;]/div[@class=&quot;controlbar_top clearfix&quot;]/div[@class=&quot;controlbar_top_main&quot;]/div[@class=&quot;l_betInfo fl&quot;]/div[@class=&quot;info_box&quot;]/div[@class=&quot;box_minus l_gameBet_minus&quot;]/span[@class=&quot;bgimgStyle bttn_minus_over&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='controlbarH5']/div/div[4]/div/div/div/div[2]/div/div[5]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bttn_minus</value>
      <webElementGuid>744e279d-463f-4efc-a5f4-03eb2fbb8752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bgimgStyle bttn_minus_over</value>
      <webElementGuid>5028fd75-e6e7-401e-b4f4-2a716fa1c137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c650b2d8-7866-4975-aa3a-f3a39391532a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unclick</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>182eaa28-31c4-48d5-83be-9f94c463fc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;controlbarH5&quot;)/div[@class=&quot;controlbarChild&quot;]/div[@class=&quot;controlbar_new_web&quot;]/div[@class=&quot;controlbarMain&quot;]/div[@class=&quot;controlbar_top clearfix&quot;]/div[@class=&quot;controlbar_top_main&quot;]/div[@class=&quot;l_betInfo fl&quot;]/div[@class=&quot;info_box&quot;]/div[@class=&quot;box_minus l_gameBet_minus&quot;]/span[@class=&quot;bgimgStyle bttn_minus_over&quot;]</value>
      <webElementGuid>7ac1ff41-8e66-4b67-8bc6-fed6aaba84bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='controlbarH5']/div/div[4]/div/div/div/div[2]/div/div[5]/span</value>
      <webElementGuid>258049ad-73fa-49f2-a60c-a826a8c84d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div[5]/span</value>
      <webElementGuid>405264f2-c0c2-47f1-a4eb-551a3bc83c2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
