<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas</name>
   <tag></tag>
   <elementGuidId>2a29d0e2-2125-46d3-b127-a276ae23363e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>4b03604e-9240-493f-9ac6-7d77b45d5cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1280</value>
      <webElementGuid>80ec97a1-3d27-4a9a-bade-4ce31d96647b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>720</value>
      <webElementGuid>ba8ec2df-0f4c-4ec5-a3e5-79c8b1847d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;wf-arialbd-n4-active wf-active&quot;]/body[1]/canvas[1]</value>
      <webElementGuid>bc27b5e8-629c-4730-8226-0961f7bd5753</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>4ad16435-f0a2-4ac1-bd0e-ee780e95c85f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
