<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_rules</name>
   <tag></tag>
   <elementGuidId>9e7c4477-1c1a-47d6-b213-e2d4893f5c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'rules' or . = 'rules')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>426f8efd-7a28-430c-90b8-0a6997358f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>cb54101f-9986-4c56-827d-dbe6481a1430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>rules</value>
      <webElementGuid>121956e3-1197-4497-b269-914f74288d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rules</value>
      <webElementGuid>9296625f-1802-4afb-adfc-246a08f69942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;royalHeader&quot;)/div[@class=&quot;ctb-header-container&quot;]/div[@class=&quot;ctb-header-right&quot;]/div[@class=&quot;icons&quot;]/div[@class=&quot;item&quot;]</value>
      <webElementGuid>34f47db4-6ec5-4dda-b855-ca0293610986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='royalHeader']/div/div[3]/div/div[3]</value>
      <webElementGuid>9ba712d8-eee3-491a-8ff3-38a941221fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='statement'])[1]/following::div[1]</value>
      <webElementGuid>c74d08bb-61ea-44e9-b695-81b977aa6837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lobby'])[1]/following::div[2]</value>
      <webElementGuid>4d06957b-537f-4b08-ac0c-4f5123e9e57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='settings'])[1]/preceding::div[1]</value>
      <webElementGuid>6ec20110-c5fa-45d5-9dac-d039f93f0408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]</value>
      <webElementGuid>ac039850-a63f-4f4a-8f72-27cb2f7efac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'rules' or . = 'rules')]</value>
      <webElementGuid>56a96a63-f167-4227-8aa7-b2616999c279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
