<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_statement</name>
   <tag></tag>
   <elementGuidId>a219b746-5f67-42cd-97d6-d5ff560639c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='royalHeader']/div/div[3]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>da68adac-fcfa-49b5-93eb-09988ccf00ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>2206fd46-7787-41f4-8ef6-0c3d6b7cff94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>statement</value>
      <webElementGuid>c436b26f-8526-4297-adfc-2108341d8907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>statement</value>
      <webElementGuid>941d8753-be15-4f30-b28d-67236faa5db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;royalHeader&quot;)/div[@class=&quot;ctb-header-container&quot;]/div[@class=&quot;ctb-header-right&quot;]/div[@class=&quot;icons&quot;]/div[@class=&quot;item&quot;]</value>
      <webElementGuid>d0a20e8f-5752-47d5-9625-fe734888c840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='royalHeader']/div/div[3]/div/div[2]</value>
      <webElementGuid>37cfc093-daa2-48f8-b0c7-ab738225bdbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lobby'])[1]/following::div[1]</value>
      <webElementGuid>f038b9be-df67-4996-9b6b-06c794de4523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[9]</value>
      <webElementGuid>abb083b0-158f-4b1f-878c-c3c2dc463bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rules'])[1]/preceding::div[1]</value>
      <webElementGuid>86a9301d-db7e-456c-93bb-8d05e9e3eb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]</value>
      <webElementGuid>0d203c0e-653f-4845-88b7-da43e9e41a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'statement' or . = 'statement')]</value>
      <webElementGuid>a757d803-24a0-4b57-ac72-96e2c1d5eb94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
