<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ANTE5</name>
   <tag></tag>
   <elementGuidId>545b7265-3283-4e30-8b42-479e0135a67a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctbTableItems']/div[3]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5c630b3a-dc9a-43d7-90fa-7cf567f4d4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-bg</value>
      <webElementGuid>30a78e6f-e7ca-4ee5-823d-fb3fa7edf456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6+ HOLD'EM ANTE 5 >> QUICK JOIN</value>
      <webElementGuid>e09398ab-fe03-4683-b65f-e7b13b7e2da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctbTableItems&quot;)/div[@class=&quot;table-bar game6&quot;]/div[@class=&quot;table-bg&quot;]</value>
      <webElementGuid>41280c96-a3e9-4cec-86c6-af982a54d9fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctbTableItems']/div[3]/div[2]</value>
      <webElementGuid>9e634d6a-796d-4b8e-99c3-e13901abdd6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>> QUICK JOIN'])[2]/following::div[3]</value>
      <webElementGuid>e3c7281b-531a-45a3-87c4-f93658ff3ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANTE 1'])[1]/following::div[3]</value>
      <webElementGuid>8cb1950e-8e3b-4df6-b9f4-1153ed25e09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>eb802438-231b-46fa-811d-f68abd1487bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;6+ HOLD&quot; , &quot;'&quot; , &quot;EM ANTE 5 >> QUICK JOIN&quot;) or . = concat(&quot;6+ HOLD&quot; , &quot;'&quot; , &quot;EM ANTE 5 >> QUICK JOIN&quot;))]</value>
      <webElementGuid>fccacd4b-a147-4e42-8c9c-357836a6e7ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
