<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_settings</name>
   <tag></tag>
   <elementGuidId>eaf64aed-7938-4b82-880c-bcda01dc371e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'settings' or . = 'settings')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f5a9b54-d859-4004-8682-2346222bf95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>2fa99375-2f2d-4267-b4fc-e878eb77655a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>settings</value>
      <webElementGuid>3e492b37-b27d-41fb-86af-f33e9297df6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>settings</value>
      <webElementGuid>28c1e05d-41a1-4e39-b30d-bd36b77ff9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;royalHeader&quot;)/div[@class=&quot;ctb-header-container&quot;]/div[@class=&quot;ctb-header-right&quot;]/div[@class=&quot;icons&quot;]/div[@class=&quot;item&quot;]</value>
      <webElementGuid>ec36a087-2299-44cc-8bea-fddc11e27f0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='royalHeader']/div/div[3]/div/div[4]</value>
      <webElementGuid>799a3370-32da-4463-9424-d5faedb50a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rules'])[1]/following::div[1]</value>
      <webElementGuid>83a372af-204b-4f1c-bf8a-8d114cb8d9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='statement'])[1]/following::div[2]</value>
      <webElementGuid>40d093de-5fbf-4d8f-a540-f7b50df6606f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GAME LOBBY'])[1]/preceding::div[1]</value>
      <webElementGuid>0aa5ea4f-ca06-45a2-bcde-44018751855b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]</value>
      <webElementGuid>43e75f61-06cc-4a9a-ad37-4b09d4cbe980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'settings' or . = 'settings')]</value>
      <webElementGuid>2228070e-6e6f-451f-a7df-aa5219506b5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
