<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_lobby</name>
   <tag></tag>
   <elementGuidId>44c56c96-cceb-4c84-9384-083dfa66e64e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'lobby' or . = 'lobby')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>074d63c9-8b0f-4185-a883-23909482ee89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>ba67fa99-733b-4d33-b9ea-d587c6a4773e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>lobby</value>
      <webElementGuid>3cf92791-6ea3-485e-9250-0cdf6060321d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>lobby</value>
      <webElementGuid>a6ceba52-d318-4008-861c-dcf22cec12e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;royalHeader&quot;)/div[@class=&quot;ctb-header-container&quot;]/div[@class=&quot;ctb-header-right&quot;]/div[@class=&quot;icons&quot;]/div[@class=&quot;item&quot;]</value>
      <webElementGuid>bd497bba-0a22-4c15-92a3-82417a8acdf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='royalHeader']/div/div[3]/div/div</value>
      <webElementGuid>2efc8652-b5e7-405a-84a0-27f1f69e91e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[8]</value>
      <webElementGuid>7ba826ca-0bc0-43ca-acb6-fb3ebb654eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/following::div[8]</value>
      <webElementGuid>b86cfdaf-b867-446a-9f47-e30468ab68a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='statement'])[1]/preceding::div[1]</value>
      <webElementGuid>f2e2c480-4caa-493b-922f-aa4c87090510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div[3]/div/div</value>
      <webElementGuid>dbeffa52-c220-40bd-bfee-d82744852a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'lobby' or . = 'lobby')]</value>
      <webElementGuid>89430ca9-4fd9-4214-ab54-64f2783a8368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
