<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ANTE1</name>
   <tag></tag>
   <elementGuidId>dbc3b05f-7bed-4986-b8d8-78018a6f0de5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctbTableItems']/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>781f8453-f2bd-4281-80a4-5267d09f48e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-bg</value>
      <webElementGuid>6eb9ddc6-d2a7-466a-a222-914e41d7a14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6+ HOLD'EM ANTE 1 >> QUICK JOIN</value>
      <webElementGuid>52ee9015-8ca2-4736-820f-b40a561d52af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctbTableItems&quot;)/div[@class=&quot;table-bar game6&quot;]/div[@class=&quot;table-bg&quot;]</value>
      <webElementGuid>08d51927-bc6d-4c28-ae50-751204417ad2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctbTableItems']/div[2]/div[2]</value>
      <webElementGuid>80860ed4-4509-495b-86ef-5574ac774081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>> QUICK JOIN'])[1]/following::div[3]</value>
      <webElementGuid>c49c4b7d-31bb-4f3d-8a87-9b4161c30e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANTE 0.50'])[1]/following::div[3]</value>
      <webElementGuid>61a5de47-8358-4ab4-80ea-9df07cc5551c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]</value>
      <webElementGuid>7782b4ec-4095-4fa0-8fa9-d82ade279a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;6+ HOLD&quot; , &quot;'&quot; , &quot;EM ANTE 1 >> QUICK JOIN&quot;) or . = concat(&quot;6+ HOLD&quot; , &quot;'&quot; , &quot;EM ANTE 1 >> QUICK JOIN&quot;))]</value>
      <webElementGuid>f9806ade-cfe0-43ed-babc-1d29f7fc0c88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
