<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Play</name>
   <tag></tag>
   <elementGuidId>b75daca4-e81d-4b0c-a9fb-42c908d8b319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@type = 'primary' and (text() = 'Play' or . = 'Play')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-1h00ux1-0.cPpUhd.sc-nv171j-7.htESxz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b11e968b-95b7-4015-97da-60643569ec16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1h00ux1-0 cPpUhd sc-nv171j-7 htESxz</value>
      <webElementGuid>5966541f-8aca-4253-a85b-c6d0d2df5a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>8bcac26b-2cb3-4c1c-9588-9406e8ec8e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play</value>
      <webElementGuid>1cef7673-dce5-41bd-bd56-0e52083bbfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appScreen&quot;)/div[@class=&quot;sc-ta30lr-0 hsHWeV&quot;]/div[@class=&quot;sc-ta30lr-2 eSnuyu&quot;]/div[@class=&quot;sc-nv171j-0 ldsJbi&quot;]/div[@class=&quot;sc-nv171j-5 eMSfuH&quot;]/div[@class=&quot;sc-1h00ux1-0 cPpUhd sc-nv171j-7 htESxz&quot;]</value>
      <webElementGuid>2cd06276-43c9-4e7f-89c9-2a2b33e704fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@type='primary']</value>
      <webElementGuid>0c909b8e-57a3-4f6d-964e-ff6381fc2dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appScreen']/div/div[5]/div[2]/div[2]/div</value>
      <webElementGuid>084cc581-3f6d-447a-9bdb-ef6b8049e04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lucky wheel'])[1]/following::div[2]</value>
      <webElementGuid>fee02121-7ef4-4b07-a59c-43ab54b84066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='online users'])[1]/following::div[133]</value>
      <webElementGuid>af16ada8-a276-40b5-b1c4-009326f0fd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hot'])[1]/preceding::div[5]</value>
      <webElementGuid>b3719c1b-2bd9-4337-9652-0300b340dcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNY'])[1]/preceding::div[13]</value>
      <webElementGuid>2bd96e9b-a769-4c29-a509-5e08f68877d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Play']/parent::*</value>
      <webElementGuid>58617fb3-93d7-42d2-b189-464853b6f7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/div</value>
      <webElementGuid>83cbb338-41d1-4d05-b3ca-ad368386f465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'primary' and (text() = 'Play' or . = 'Play')]</value>
      <webElementGuid>8517f5df-a6fc-47a7-ac3b-0c812e4c0af4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
