<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_FeatureBuyAmountDecrease</name>
   <tag></tag>
   <elementGuidId>393689e5-6a0a-4a7f-b5ea-fa35a3755371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='FeatureBuyAmountDecrease']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FeatureBuyAmountDecrease</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf506f01-f1ee-4790-86d7-98fc00295ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FeatureBuyAmountDecrease</value>
      <webElementGuid>290f2cd4-d978-4207-8efb-eee302b4f792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FeatureBuyAmountChanger</value>
      <webElementGuid>59465bcd-8859-4136-b8db-30e7f7a62eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FeatureBuyAmountDecrease&quot;)</value>
      <webElementGuid>aac608ab-1d1d-4e1a-b1c6-3da357cbe7ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='FeatureBuyAmountDecrease']</value>
      <webElementGuid>b07103b5-72d2-4029-bb78-c0acf7a939ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FeatureBuyAmountHolder']/div[2]/button[2]</value>
      <webElementGuid>1de0fa45-0cf4-47b4-8a0f-e65b03172d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥10.00'])[1]/following::button[2]</value>
      <webElementGuid>edbc8638-a74e-4004-aa86-e075df7fd3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BET'])[2]/following::button[2]</value>
      <webElementGuid>03feba4d-fb36-4be0-a002-d20008b06346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MULTI-COLOR FREE SPINS'])[1]/preceding::button[1]</value>
      <webElementGuid>9001e2d2-bfdd-4795-bfb5-ef416a267795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥1,090.00'])[1]/preceding::button[1]</value>
      <webElementGuid>770517dc-b16f-4548-b52b-50eb1929c667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>31ee0fbe-9354-4e27-b674-583a2977f84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'FeatureBuyAmountDecrease']</value>
      <webElementGuid>9cda724d-fa0d-43a3-a552-7cb3e602f4e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
