<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_FeatureBuyAmountIncrease</name>
   <tag></tag>
   <elementGuidId>f0e14774-2816-4404-877b-524620d5c4d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='FeatureBuyAmountIncrease']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FeatureBuyAmountIncrease</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce64f772-b284-47ae-b1d6-24a96c738573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FeatureBuyAmountIncrease</value>
      <webElementGuid>e734261a-4ea8-482b-b68e-81eec4425631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FeatureBuyAmountChanger</value>
      <webElementGuid>a390d4a5-c69c-4eb4-b36b-3f1c3f700b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FeatureBuyAmountIncrease&quot;)</value>
      <webElementGuid>1f66454d-3bd2-47d9-8d82-b61e6b9b3bbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='FeatureBuyAmountIncrease']</value>
      <webElementGuid>39b96f1b-dc8b-49b9-a752-052112f0f7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FeatureBuyAmountHolder']/div[2]/button</value>
      <webElementGuid>ea1711b8-9a29-4d05-a5aa-e693d644eba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥10.00'])[1]/following::button[1]</value>
      <webElementGuid>5e742126-141a-4e61-aaa0-b88ef7229201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BET'])[2]/following::button[1]</value>
      <webElementGuid>1e88c4b0-095e-49c5-96c3-39dd4216c9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MULTI-COLOR FREE SPINS'])[1]/preceding::button[2]</value>
      <webElementGuid>d9e23574-bd9a-470d-b3a8-4a8390736c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¥1,090.00'])[1]/preceding::button[2]</value>
      <webElementGuid>e54b9972-da89-41a4-949a-a0484725c345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>9c48a065-f2e6-4778-aa9e-2225d3bf756b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'FeatureBuyAmountIncrease']</value>
      <webElementGuid>c9b008f3-3468-4d13-a288-5bd0505e3327</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
