<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_turbo OFF</name>
   <tag></tag>
   <elementGuidId>0f9a53b9-5047-42d4-9a46-0af2fcffcbe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.button-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gameControlPanel']/div/div[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3f8ebaf1-2393-49e3-91d3-7eac300c711f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdndemo2.jdb199.info/games/game_container/flat_ui/turbo-off.svg</value>
      <webElementGuid>ed022e7c-d17c-4a9f-9614-a1498152ef8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>turbo-off</value>
      <webElementGuid>e03cd22e-a5cc-4889-b225-cdbcf066aa34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-icon</value>
      <webElementGuid>09a691f6-46a7-48bf-a00f-ca22e105ffcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gameControlPanel&quot;)/div[@class=&quot;control-panel-container&quot;]/div[@class=&quot;operation-section&quot;]/div[@class=&quot;operation-wrapper&quot;]/div[@class=&quot;button-turbo&quot;]/img[@class=&quot;button-icon&quot;]</value>
      <webElementGuid>2edb55ab-f2b9-4009-9775-766304c3d2df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gameControlPanel']/div/div[3]/div/div/img</value>
      <webElementGuid>ae6bdb03-ac33-4271-851b-cbed6e98b53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='turbo-off']</value>
      <webElementGuid>f1e61920-f51d-42f7-9f7f-70c50d928b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img</value>
      <webElementGuid>609ad6e7-da32-4e25-b7dd-85bf37bbd255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdndemo2.jdb199.info/games/game_container/flat_ui/turbo-off.svg' and @alt = 'turbo-off']</value>
      <webElementGuid>c07ab292-9a72-4174-880c-a958af505eae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
