<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_auto spin</name>
   <tag></tag>
   <elementGuidId>2224e72b-a047-448b-b38e-7e689e661848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.button-auto-spin > img.button-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='autospin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5c303853-0813-476e-85c9-24df84c8df94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdndemo2.jdb199.info/games/game_container/flat_ui/autospin.svg</value>
      <webElementGuid>513e343a-48c9-4b04-8395-1c870a9e9ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>autospin</value>
      <webElementGuid>24e2abc9-2b93-41f4-a7a7-6d5c90d2c28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-icon</value>
      <webElementGuid>e0fca6ef-3911-4f01-b6f9-1fc46cf3f351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gameControlPanel&quot;)/div[@class=&quot;control-panel-container&quot;]/div[@class=&quot;operation-section&quot;]/div[@class=&quot;operation-wrapper&quot;]/div[@class=&quot;button-auto-spin&quot;]/img[@class=&quot;button-icon&quot;]</value>
      <webElementGuid>6595b4f6-ff85-418e-bdbf-21590063037d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gameControlPanel']/div/div[3]/div/div[5]/img</value>
      <webElementGuid>508ab6cc-b961-4be2-b5d1-68241d188e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='autospin']</value>
      <webElementGuid>3d372d91-6df8-4dcf-9b49-b5c5a8fe8746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/img</value>
      <webElementGuid>4b3aaff3-26c7-422f-b878-3143913a9300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdndemo2.jdb199.info/games/game_container/flat_ui/autospin.svg' and @alt = 'autospin']</value>
      <webElementGuid>404ce9a5-e6a7-4e9d-a6b5-54c7634e6088</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
