<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_increase</name>
   <tag></tag>
   <elementGuidId>b1305847-9e5c-4b35-98a8-f330f09c914a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.button-bet-increase > img.button-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='increase']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>206264e5-f1e9-4a35-9bea-7493f53c6202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdndemo2.jdb199.info/games/game_container/flat_ui/increase.svg</value>
      <webElementGuid>50cd2c8d-3bd4-486c-9ce0-5234f91c34bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>increase</value>
      <webElementGuid>70b2a5dd-0d29-43b9-bebf-601223e78b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-icon</value>
      <webElementGuid>174a9dec-6bc0-450d-8e04-99847ac62869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gameControlPanel&quot;)/div[@class=&quot;control-panel-container&quot;]/div[@class=&quot;operation-section&quot;]/div[@class=&quot;operation-wrapper&quot;]/div[@class=&quot;button-bet-increase&quot;]/img[@class=&quot;button-icon&quot;]</value>
      <webElementGuid>e9082d45-490a-4ac3-b528-3aaeb08779b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gameControlPanel']/div/div[3]/div/div[4]/img</value>
      <webElementGuid>a336bcdf-b01b-4997-8021-a4b37668cc22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='increase']</value>
      <webElementGuid>46ab4556-da6e-468e-ad34-d127580b0234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/img</value>
      <webElementGuid>3fc02988-c139-41b8-a7ad-a7f50682ce7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdndemo2.jdb199.info/games/game_container/flat_ui/increase.svg' and @alt = 'increase']</value>
      <webElementGuid>92d6ea25-921d-47f5-bf10-9f54464a0082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
