<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_spin</name>
   <tag></tag>
   <elementGuidId>6659ebaf-00d8-4190-bf7e-9eabe2aee3c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.button-spin > img.button-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gameControlPanel']/div/div[3]/div/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f917d0ee-34f0-416f-8cc8-60db530517f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdndemo2.jdb199.info/games/game_container/flat_ui/spin.svg</value>
      <webElementGuid>aa1dc5f9-e515-4906-b61a-1957cf2d4133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>spin</value>
      <webElementGuid>ba9a8c61-d489-4dbe-a9e4-e01e71e6377a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-icon</value>
      <webElementGuid>0619b6df-3baa-4c78-be9a-2b8b673ec3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gameControlPanel&quot;)/div[@class=&quot;control-panel-container&quot;]/div[@class=&quot;operation-section&quot;]/div[@class=&quot;operation-wrapper&quot;]/div[@class=&quot;button-spin&quot;]/img[@class=&quot;button-icon&quot;]</value>
      <webElementGuid>d78db3cd-1c1e-4d1d-8b05-53cbf6a7ac5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gameControlPanel']/div/div[3]/div/div[3]/img</value>
      <webElementGuid>9071f957-7dc1-42ed-98b6-00528ee57273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='spin']</value>
      <webElementGuid>c8cd3f71-829c-412b-9832-10c740ebb9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>efc81143-dd4d-4c6b-8e89-c8d3e9345a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdndemo2.jdb199.info/games/game_container/flat_ui/spin.svg' and @alt = 'spin']</value>
      <webElementGuid>9814b577-577f-4ec4-a603-fe795c90d745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
