<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_decrease</name>
   <tag></tag>
   <elementGuidId>3a89619f-0a1c-4cec-830e-8855b2344615</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.button-bet-decrease > img.button-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='decrease']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>29c7e25a-e48f-4eea-b6e4-772e23d91e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdndemo2.jdb199.info/games/game_container/flat_ui/decrease.svg</value>
      <webElementGuid>c4f195e9-9f80-48c2-8c34-2cf793417750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>decrease</value>
      <webElementGuid>02fda2a6-a300-48fe-abbd-932a3c812962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-icon</value>
      <webElementGuid>1fe82ef2-1318-453b-8cd4-1652ab7c573f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gameControlPanel&quot;)/div[@class=&quot;control-panel-container&quot;]/div[@class=&quot;operation-section&quot;]/div[@class=&quot;operation-wrapper&quot;]/div[@class=&quot;button-bet-decrease&quot;]/img[@class=&quot;button-icon&quot;]</value>
      <webElementGuid>46292e7b-43e3-42a3-b77e-68f4816a49c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gameControlPanel']/div/div[3]/div/div[2]/img</value>
      <webElementGuid>02761543-5f58-4ce4-a25f-6c2da49b0294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='decrease']</value>
      <webElementGuid>30b7b10a-f4eb-4385-adab-447eec6544ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/img</value>
      <webElementGuid>3f71d0f5-e7c2-40af-b291-b4d1f2356ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdndemo2.jdb199.info/games/game_container/flat_ui/decrease.svg' and @alt = 'decrease']</value>
      <webElementGuid>8d7ab276-9396-4f7b-a3e0-6027015b3899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
