<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_turbo ON</name>
   <tag></tag>
   <elementGuidId>b51e82db-c50e-4743-8597-e391649c1238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.button-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gameControlPanel']/div/div[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9797973f-5496-4814-b8e9-5a80cdfbb6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdndemo2.jdb199.info/games/game_container/flat_ui/turbo-on.svg</value>
      <webElementGuid>43647031-5260-4fbc-a1a8-24d9b04c024d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>turbo-on</value>
      <webElementGuid>42883060-3ebf-4547-b677-2cf2a14cd371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-icon</value>
      <webElementGuid>b5fbb7af-87f3-4e33-926e-ff638a48fec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gameControlPanel&quot;)/div[@class=&quot;control-panel-container&quot;]/div[@class=&quot;operation-section&quot;]/div[@class=&quot;operation-wrapper&quot;]/div[@class=&quot;button-turbo&quot;]/img[@class=&quot;button-icon&quot;]</value>
      <webElementGuid>e48e1f79-8335-40f9-843a-c832e6373f5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gameControlPanel']/div/div[3]/div/div/img</value>
      <webElementGuid>b2d0d7db-dc6d-4a29-b5fc-c28ae82abde8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='turbo-on']</value>
      <webElementGuid>feb3fba7-ff5e-4cc2-834d-88c2ea142230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img</value>
      <webElementGuid>a7287065-8dce-4c13-b48a-544a8af67e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdndemo2.jdb199.info/games/game_container/flat_ui/turbo-on.svg' and @alt = 'turbo-on']</value>
      <webElementGuid>1878c985-ad56-43ea-be62-dbbda7b594d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
