<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_MUSIC_icon-turbo</name>
   <tag></tag>
   <elementGuidId>434df1a5-88e4-472e-a269-6d955218794c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='TurboToggle']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon-turbo-off</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TurboToggle span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>80149730-19b7-47a6-8420-441ce1f10372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-turbo-off</value>
      <webElementGuid>7b3c567f-1371-4d0c-884e-cc60744106ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TurboToggle&quot;)/span[@class=&quot;icon-turbo-off&quot;]</value>
      <webElementGuid>6434d518-0268-4b7e-adbd-c8c79ce01b4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='TurboToggle']/span</value>
      <webElementGuid>6824f12a-e6d8-42ee-baa3-87507b9166ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span</value>
      <webElementGuid>6d820aa1-a930-4fc0-a026-a30924483c1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
