<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SOUND_icon-music</name>
   <tag></tag>
   <elementGuidId>dcb6dda1-8f36-451a-a3db-a4f4a9c92b51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='MusicToggle']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon-music-on</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MusicToggle span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>455e4ca6-b603-44cb-b5ee-0a4dc053aec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-music-on</value>
      <webElementGuid>c68f3c0f-228f-4707-b305-04f602baf08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MusicToggle&quot;)/span[@class=&quot;icon-music-on&quot;]</value>
      <webElementGuid>e12c9a73-6787-4574-9824-e086290dcb10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='MusicToggle']/span</value>
      <webElementGuid>8a85349b-869e-455b-bb71-b26e05f6acd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>7ce16fdd-20a0-490c-aa2a-8cdec6c92e82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
