<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_HISTORY_icon-info</name>
   <tag></tag>
   <elementGuidId>6ba6a756-d6b9-4a92-8611-65fe6cba7a9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='GameInfoBtn']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon-info-a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#GameInfoBtn span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>46d07032-7c48-4cf2-81cb-1c183c7b7fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-info-a</value>
      <webElementGuid>b7e914cb-d1e1-4235-b245-369e9021f4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GameInfoBtn&quot;)/span[@class=&quot;icon-info-a&quot;]</value>
      <webElementGuid>552dbd54-858f-4768-9cc6-781ea8bb72e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='GameInfoBtn']/span</value>
      <webElementGuid>954cb8d8-1d70-4d84-b946-2e1763e2055e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/span</value>
      <webElementGuid>f41e2e2d-cd90-49ad-b93f-ecaa345c1fdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
