<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_TURBO_icon-history</name>
   <tag></tag>
   <elementGuidId>ef2dcb21-4b44-4d5e-bf68-588a3647a938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='BetHistoryBtn']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon-history</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#BetHistoryBtn span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14576b97-e8ff-4e5f-9d6d-0ab4600ac917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-history</value>
      <webElementGuid>eee54c5c-7974-4cac-9b4b-0464d2ad6208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BetHistoryBtn&quot;)/span[@class=&quot;icon-history&quot;]</value>
      <webElementGuid>01648a6b-a081-4be1-960f-7556bcdb179b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='BetHistoryBtn']/span</value>
      <webElementGuid>b0772856-5890-481b-b81d-7b9fcbc4419f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/span</value>
      <webElementGuid>a133d5a1-a943-4d97-b900-f74db8b890cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
