<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_All</name>
   <tag></tag>
   <elementGuidId>760136ef-e3e7-4153-befc-0f0a7c564d90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-1c6c2ql-1.llktwZ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appScreen']/div/div[3]/div[6]/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.sc-1c6c2ql-1 >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f4fcf219-f4a5-418b-be84-1d9bb79a4909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1.5rem</value>
      <webElementGuid>e04c9ce2-7b9c-4cd1-8103-4b3114562060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1.5rem</value>
      <webElementGuid>9c3a83d7-34ce-41bb-bf29-24dca2eae495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1c6c2ql-1 llktwZ</value>
      <webElementGuid>a5d4592c-54e0-456d-a254-4f296f2d8292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appScreen&quot;)/div[@class=&quot;sc-ta30lr-0 hsHWeV&quot;]/div[@class=&quot;sc-ta30lr-2 iYbVsY&quot;]/div[@class=&quot;sc-nj6x7d-0 iksVaR&quot;]/div[@class=&quot;sc-lr01sa-0 eZaASS&quot;]/div[@class=&quot;sc-lr01sa-1 FfObA&quot;]/div[@class=&quot;sc-1c6c2ql-0 ifIqbH&quot;]/div[@class=&quot;sc-1c6c2ql-1 llktwZ&quot;]</value>
      <webElementGuid>7b5b29d9-2ea2-4471-a47f-d4ba424529d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appScreen']/div/div[3]/div[6]/div/div/div/div[2]</value>
      <webElementGuid>73196b69-d297-4509-9b0e-c1572061d9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]</value>
      <webElementGuid>f4f3e716-edd5-425c-8ac2-51d81da311ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appScreen']/div/div[3]/div[2]/div/div</value>
      <webElementGuid>2014d2b9-e861-4606-bd42-b56e8d0cb2c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='online users'])[1]/following::div[35]</value>
      <webElementGuid>d542ee60-4884-4161-82d7-a27818d76d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::div[1]</value>
      <webElementGuid>29efb3aa-144a-467d-ba76-1f96d99ad577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/preceding::div[3]</value>
      <webElementGuid>e9e6a570-7dd8-48ff-8f20-9a44967aaea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div</value>
      <webElementGuid>5c358746-ba5e-4691-9e12-fe213ecb43e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
