<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Macau</name>
   <tag></tag>
   <elementGuidId>b3f7ee0f-b9ec-4325-a987-295fab163b22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Macau'])[1]/preceding::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(6) > .sc-k2dsw9-0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5abc51ca-fe1b-4794-ab8a-ceb8b66ae123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1.5rem</value>
      <webElementGuid>3ca25ee9-4d5c-43f4-968a-a8be06b71b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1.5rem</value>
      <webElementGuid>7b7087f6-07cb-409b-8228-3ab62069e58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-k2dsw9-0 estWHx sc-1g7b8gk-1 gXoyhc</value>
      <webElementGuid>c0ff4518-3ffe-4415-93bf-0e92042fd931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appScreen&quot;)/div[@class=&quot;sc-ta30lr-0 hsHWeV&quot;]/div[@class=&quot;sc-ta30lr-2 iYbVsY&quot;]/div[@class=&quot;sc-1g7b8gk-0 hOIlsq&quot;]/div[@class=&quot;sc-1g7b8gk-3 gOGYEA&quot;]/div[@class=&quot;sc-k2dsw9-0 estWHx sc-1g7b8gk-1 gXoyhc&quot;]</value>
      <webElementGuid>3726202b-0c86-436f-862a-d011620905cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appScreen']/div/div[3]/div[2]/div[6]/div</value>
      <webElementGuid>e5e3a904-3bfe-4fe4-ac92-f023311fa0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asia'])[1]/following::div[2]</value>
      <webElementGuid>8befb0d7-5784-4eb2-9379-a48838754f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GOF'])[1]/following::div[5]</value>
      <webElementGuid>8e10797c-0639-4048-bc90-22d99f86a466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Macau'])[1]/preceding::div[1]</value>
      <webElementGuid>24b0a31d-9190-4d6f-a75b-e7b091ec328a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Others'])[1]/preceding::div[3]</value>
      <webElementGuid>c7f73bc0-23c9-4ea2-92ff-9754f70cc9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/div</value>
      <webElementGuid>b291d15a-a38c-48f7-a275-94c8403840cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
