<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Play</name>
   <tag></tag>
   <elementGuidId>0d6d2f1b-cea0-4a7b-9171-2ec34d2caad5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Play']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-1h00ux1-0.kxnBqC.sc-1fq5omn-9.iiorrY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Play&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>578b25b3-47f0-4058-9794-26da5b70c28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1h00ux1-0 kxnBqC sc-1fq5omn-9 iiorrY</value>
      <webElementGuid>034af605-5ac7-43cc-91b7-900fe3576291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>070dd743-9087-4446-8199-180565be76ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play</value>
      <webElementGuid>8e5622eb-24e6-466b-9766-e6a7a17e1c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appScreen&quot;)/div[@class=&quot;sc-ta30lr-0 hsHWeV&quot;]/div[@class=&quot;sc-ta30lr-2 iYbVsY&quot;]/div[@class=&quot;sc-nj6x7d-0 iksVaR&quot;]/div[@class=&quot;sc-lr01sa-0 eZaASS&quot;]/div[@class=&quot;sc-lr01sa-1 FfObA&quot;]/div[@class=&quot;sc-1c6c2ql-0 ifIqbH&quot;]/div[@class=&quot;sc-1c6c2ql-2 ivBIpX&quot;]/div[@class=&quot;sc-13l6pns-0 hrCmpp&quot;]/div[@class=&quot;sc-1fq5omn-1 gusJXv&quot;]/div[@class=&quot;sc-1h00ux1-0 kxnBqC sc-1fq5omn-9 iiorrY&quot;]</value>
      <webElementGuid>c70a55b2-7c2a-486d-a366-0625bb66e322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@type='primary']</value>
      <webElementGuid>e88befce-4487-4a4e-bc2a-f122563f8b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appScreen']/div/div[3]/div[6]/div/div/div/div[2]/div/div[3]/div[3]</value>
      <webElementGuid>6dcd7f3f-061f-4c99-93c9-705b19ae8c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VictoriaS 1'])[2]/following::div[26]</value>
      <webElementGuid>9c358e28-db14-40fc-add1-5c566c66f3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VictoriaS 1'])[1]/following::div[47]</value>
      <webElementGuid>8c4404af-b4de-4f80-8c45-1cbfabc8ce05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Player'])[1]/preceding::div[13]</value>
      <webElementGuid>e2816708-a2ab-4655-bfdb-4f2defa932aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banker'])[1]/preceding::div[30]</value>
      <webElementGuid>5dcf8681-7218-4be6-b4e1-fac5a7e7ed0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Play']/parent::*</value>
      <webElementGuid>4a5fd32c-4578-4cbc-958a-d8bcb51e7b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div[3]</value>
      <webElementGuid>551a13a4-e7e3-402e-9ba2-0a5571faf6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'primary' and (text() = 'Play' or . = 'Play')]</value>
      <webElementGuid>3b8a522d-025c-414c-a9bd-007a98aef285</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
