<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_150.00</name>
   <tag></tag>
   <elementGuidId>aad82777-baae-44ac-b374-9bc713617cb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = '150.00' or . = '150.00')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9b3ec0a5-6fbe-4b10-a170-6182ea1c215a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bet_li</value>
      <webElementGuid>e7f5d322-f548-4e71-bec6-e2b26eee642f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>b868019f-670b-4797-872d-198d8661798a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>150.00</value>
      <webElementGuid>4a95f856-8159-401b-a254-a0d594674981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;controlbarH5&quot;)/div[@class=&quot;controlbarChild&quot;]/div[@class=&quot;controlbar_new_web&quot;]/div[@class=&quot;controlbarMain&quot;]/div[@class=&quot;controlbar_top clearfix&quot;]/div[@class=&quot;controlbar_top_main&quot;]/div[@class=&quot;l_betInfo fl&quot;]/div[@class=&quot;info_bet_list&quot;]/div[@class=&quot;bet_ul&quot;]/div[@class=&quot;bet_li&quot;]</value>
      <webElementGuid>44c5f371-2c7e-4d06-afcb-aae601f6437d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='controlbarH5']/div/div[4]/div/div/div/div[2]/div[2]/div[2]/div[3]</value>
      <webElementGuid>82037eb2-df7e-44ad-a7a0-62d23d3fb78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[1]/following::div[22]</value>
      <webElementGuid>68d36fe2-555b-4739-9eff-c752acfa44c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bet'])[1]/following::div[24]</value>
      <webElementGuid>866e45af-d3cc-424b-9f8d-a002f86b574a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credits'])[1]/preceding::div[7]</value>
      <webElementGuid>1c40772b-573d-4e79-897c-321927ed8456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[2]/preceding::div[9]</value>
      <webElementGuid>378f4247-f8eb-48ba-a820-e2217ab8d763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='150.00']/parent::*</value>
      <webElementGuid>f565547b-c634-42ff-a505-a0756fbd787f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[3]</value>
      <webElementGuid>82ce4230-b21b-45b1-a294-30332d31f46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '150.00' or . = '150.00')]</value>
      <webElementGuid>a1bdeb0f-756e-4726-9536-8afea69a3c4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
