<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_10.00</name>
   <tag></tag>
   <elementGuidId>35ac4a91-3694-4e2e-9faf-fd42b28f85b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = '10.00' or . = '10.00')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2f211a9b-da56-49a5-a8b9-c5e42065f295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bet_li</value>
      <webElementGuid>d2894f62-7bd6-4161-8550-e632ea9c0a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>c18830b3-9596-4086-8eb0-3aab480996df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10.00</value>
      <webElementGuid>b4798d2c-de1f-4962-84e0-38cf3875b512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;controlbarH5&quot;)/div[@class=&quot;controlbarChild&quot;]/div[@class=&quot;controlbar_new_web&quot;]/div[@class=&quot;controlbarMain&quot;]/div[@class=&quot;controlbar_top clearfix&quot;]/div[@class=&quot;controlbar_top_main&quot;]/div[@class=&quot;l_betInfo fl&quot;]/div[@class=&quot;info_bet_list&quot;]/div[@class=&quot;bet_ul&quot;]/div[@class=&quot;bet_li&quot;]</value>
      <webElementGuid>a88171d7-fb21-46c5-ac29-9a5bd157f5a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='controlbarH5']/div/div[4]/div/div/div/div[2]/div[2]/div/div[7]</value>
      <webElementGuid>eb3feea5-1cff-472e-aea2-76208db26e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[1]/following::div[15]</value>
      <webElementGuid>d1dcc297-8fe4-4e9d-8b6a-3dba10605832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bet'])[1]/following::div[17]</value>
      <webElementGuid>74d90906-b32e-4770-b304-128b783965be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credits'])[1]/preceding::div[14]</value>
      <webElementGuid>d7fdb0ab-e8ee-494d-93ce-225f97cb1e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[2]/preceding::div[16]</value>
      <webElementGuid>5c3cab55-68cd-474a-8205-1c2b72c1acd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10.00']/parent::*</value>
      <webElementGuid>edacf36a-3c47-4b0c-863e-eac53243f935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[7]</value>
      <webElementGuid>75bc7b51-cc77-4c4d-a02d-819b5166cb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '10.00' or . = '10.00')]</value>
      <webElementGuid>aa0feb46-c381-41cd-9888-110f039653c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
