<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_600.00</name>
   <tag></tag>
   <elementGuidId>02bf094a-ccdd-431b-92ef-ac1c7f013ed3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = '600.00' or . = '600.00')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ce461acc-7f7d-4b8c-9209-a650f01213b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bet_li</value>
      <webElementGuid>ea89459f-a568-404c-a5f0-67474453fee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>977d19ef-68a4-4fc5-aba3-1b66caf0cb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>600.00</value>
      <webElementGuid>4fde8f8c-4ce3-4c24-af93-849a2de46bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;controlbarH5&quot;)/div[@class=&quot;controlbarChild&quot;]/div[@class=&quot;controlbar_new_web&quot;]/div[@class=&quot;controlbarMain&quot;]/div[@class=&quot;controlbar_top clearfix&quot;]/div[@class=&quot;controlbar_top_main&quot;]/div[@class=&quot;l_betInfo fl&quot;]/div[@class=&quot;info_bet_list&quot;]/div[@class=&quot;bet_ul&quot;]/div[@class=&quot;bet_li&quot;]</value>
      <webElementGuid>23338b0c-ab03-4bcf-949b-ad5116f129c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='controlbarH5']/div/div[4]/div/div/div/div[2]/div[2]/div[2]/div[7]</value>
      <webElementGuid>97c108a7-2cec-4cd2-8e38-191c57ae1948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[1]/following::div[26]</value>
      <webElementGuid>0440b369-88be-4b8e-b1cf-7779042dd3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bet'])[1]/following::div[28]</value>
      <webElementGuid>abfe9d94-ed29-4871-a1e7-81034cc86292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credits'])[1]/preceding::div[3]</value>
      <webElementGuid>48646784-2d60-4dce-96f5-74254a6190bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[2]/preceding::div[5]</value>
      <webElementGuid>14439f69-3d44-4a47-bf93-d68487968ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='600.00']/parent::*</value>
      <webElementGuid>a0271708-17d7-40cd-815f-75f116fcdf22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[7]</value>
      <webElementGuid>04100312-068e-4bf2-810d-6556a49a8a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '600.00' or . = '600.00')]</value>
      <webElementGuid>5ca4f87b-aaad-4872-ba19-11795be24468</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
