<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas</name>
   <tag></tag>
   <elementGuidId>2bd6adfc-4c11-4662-bd34-2da5527ad02d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jdbGameContainer']/div/div[2]/div/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>724eff02-e9f5-4755-acc2-2f1b835e25d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1280</value>
      <webElementGuid>26641759-9fe5-4ab1-b8b9-2ba411e59872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>720</value>
      <webElementGuid>c7a202c1-884c-4bc8-b6b5-ab574c7bdbcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jdbGameContainer&quot;)/div[@class=&quot;jdbGamePage&quot;]/div[@class=&quot;gameReel&quot;]/div[@class=&quot;egret-player&quot;]/canvas[1]</value>
      <webElementGuid>a1e58f25-11c3-4fd5-9629-f887a7005ed1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jdbGameContainer']/div/div[2]/div/canvas</value>
      <webElementGuid>f4e51a8e-c04c-400c-b849-feeb5d394d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>3f2e782c-9e6f-43a1-ac87-d7f8a1d4a05f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
