<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas</name>
   <tag></tag>
   <elementGuidId>829995c8-bdc9-4e6e-b16d-7f91ba81a609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GameCanvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id = 'GameCanvas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>24fd9ab0-5453-4948-b817-285ca0618f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GameCanvas</value>
      <webElementGuid>795fb3f8-83f3-4741-99d1-b01f3da3f47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncontextmenu</name>
      <type>Main</type>
      <value>event.preventDefault()</value>
      <webElementGuid>de8f36c4-bc74-465b-8702-3d218591b965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>99</value>
      <webElementGuid>528d807f-c6b1-4866-947e-a425d15c195f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gameCanvas</value>
      <webElementGuid>e8ca527d-3807-45b5-9441-6cb2d3ff8170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1920</value>
      <webElementGuid>e0d7ebf9-d50c-4f93-a2e1-a60d33e6e675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>911</value>
      <webElementGuid>f25c0559-8540-4563-986d-6c65e051d809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GameCanvas&quot;)</value>
      <webElementGuid>7c6feec4-f393-41a8-bdac-f564c909c1e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='GameCanvas']</value>
      <webElementGuid>79a557ff-3005-4d67-b060-5e1ac5106411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Cocos2dGameContainer']/canvas</value>
      <webElementGuid>9620f45d-6dc5-4338-b89f-76973a6a98de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>eed7ae59-7fb8-418d-b8d0-9ef931b309d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'GameCanvas']</value>
      <webElementGuid>1b38b052-14f8-4b09-888b-b4a96e26b664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
